### ISSUE TITLE
Add support for aten::gru_cell

### ISSUE THREAD

**Issue by abhi-iyer** [NVIDIA/TRTorch#109]
## aten::gru_cell

- **Function Schema**: gru_cell(Tensor input, Tensor hx, Tensor w_ih, Tensor w_hh, Tensor? b_ih=None, Tensor? b_hh=None) -> Tensor

- **Original PyTorch API**: https://pytorch.org/docs/master/generated/torch.nn.GRUCell.html

- **Relevant TensorRT Documentation**:

**Comment by narendasan** [comment]
cc: @arvindsridhar

**Comment by narendasan** [comment]
https://github.com/onnx/onnx-tensorrt/blob/a80015b29668722bc4d8e226f64c3fe8edf60179/builtin_op_importers.cpp#L1548
