### ISSUE TITLE
Can't compile python package

### ISSUE THREAD

**Issue by IgnacioJPickering** [NVIDIA/TRTorch#130]
I am able to compile the CXX API, but the python package fails with the error:

```
fatal error: NvInfer.h: No such file or directory
 #include "NvInfer.h"
          ^~~~~~~~~~~
compilation terminated.
```
A quick search confirms that ``NvInfer.h`` is not in the repo, so I assume it is part of LibTorch / cuDNN / TRT, so I suspect bazel has an issue with the location of one of these, but I find it strange that I can compile the C++ API, so I was wondering if the python package is currently building correctly and, if so, what I can do to troubleshoot this.
My OS is Ubuntu 20.04, python 3.8 inside a conda environment, with bazel 3.3.1, cuda 10.2, TensorRT 7.1.3.4 and cuDNN 8.0.1.13

**Comment by narendasan** [comment]
Is it possible to tell if this error is coming from Ninja or Bazel? My guess is that it is coming from Ninja when compiling the PyBind module (post compilation of the core library).  We include TensorRT headers here for the python package build https://github.com/NVIDIA/TRTorch/blob/842a56723b74f64ca13001f66f2c396dfe19cc30/py/setup.py#L150 to use bazel managed dependencies. Are you pulling in dependencies with `http_archive/dist_dir` or using locally installed TensorRT/cuDNN?
