### ISSUE TITLE
Use of non-public PyTorch op registration API

### ISSUE THREAD

**Issue by smessmer** [NVIDIA/TRTorch#131]
We noticed that you're using a non-public PyTorch operator registration API in https://github.com/NVIDIA/TRTorch/blob/223d8ddf9301a3fcb68167757a3f997b9e0c7d45/core/execution/register_trt_op.cpp#L58. This API works, but it's not public API and there are no bc guarantees for it.

Does the public operator registration API (see [here](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html)) work for you? If not, we'd like to know why so we can improve that API.

**Comment by narendasan** [comment]
We didn't really know about this API when we built out the executor phase. I'll take a look at this API and see if it will work for us so we are on stable APIs.

**Comment by zhiqwang** [comment]
Hi, @narendasan , Thanks for your awesome work. I noticed that the TRTorch have updated with pytorch 1.6, is there any updates with PyTorch op registration here?
