### ISSUE TITLE
🐛 [Bug] Fail to build the NVIDIA TRTorch container on AGX device with JetPack 4.4

### ISSUE THREAD

**Issue by chiehpower** [NVIDIA/TRTorch#139]
##  Bug Description

I was following this page of [instruction](https://github.com/NVIDIA/TRTorch/tree/master/notebooks#1-requirements).

Command:
```
$ sudo docker build -t trtorch -f Dockerfile.notebook .
```

Output:
```
[sudo] password for nvidia: 
Sending build context to Docker daemon  44.18MB
Step 1/14 : FROM nvcr.io/nvidia/pytorch:20.03-py3
20.03-py3: Pulling from nvidia/pytorch
423ae2b273f4: Pulling fs layer 
de83a2304fa1: Pulling fs layer 
f9a83bce3af0: Pulling fs layer 
b6b53be908de: Waiting 
031ae32ea045: Waiting 
2e90bee95401: Waiting 
23b28e4930eb: Waiting 
440cfb09d608: Waiting 
6f3b05de36c6: Waiting 
b0444ce283f5: Waiting 
8326831bdd40: Waiting 
6cb1b0c70efa: Waiting 
51bcf8ebb1f7: Waiting 
69bbced5c7a2: Waiting 
5f6e40c02ff4: Waiting 
ca7835aa5ed2: Waiting 
4c512b1ff8a5: Waiting 
d85924290896: Waiting 
97bb0d3f884c: Waiting 
56a4e3b147c2: Waiting 
468df4aef4c6: Waiting 
522d2b613df7: Pulling fs layer 
7d6417f56587: Pulling fs layer 
522d2b613df7: Waiting 
7d6417f56587: Waiting 
0ccda1e4ca15: Waiting 
18244f890475: Waiting 
c7986e09dff5: Waiting 
2d210642f30c: Waiting 
c564a113d3bd: Waiting 
44abac184be5: Waiting 
61817282129e: Waiting 
77b3c5340637: Waiting 
e7911ce14988: Waiting 
59bc17a4d14a: Waiting 
6b2f7c275865: Pull complete 
07c633be5574: Pull complete 
6d767ce36c21: Pull complete 
46bbec03f88b: Pull complete 
96da7d87df89: Pull complete 
d2663f680b06: Pull complete 
0ed7e2db20ab: Pull complete 
afd57a3ccf55: Pull complete 
19ac17f49e57: Pull complete 
2984c7bac0e3: Pull complete 
e2244eb6a8e7: Pull complete 
070f20eb03a3: Pull complete 
f6580f25c383: Pull complete 
7cc17e0c99d8: Pull complete 
aaf5c91bb3d5: Pull complete 
c9ad85820d20: Pull complete 
e4aaec5cb4a5: Pull complete 
3965323727b2: Pull complete 
5d75d4272baf: Pull complete 
318400c074f7: Pull complete 
b5295904374f: Pull complete 
b962e5b89d31: Pull complete 
fe830d24a0da: Pull complete 
Digest: sha256:5f7b67b14fed35890e06f8f4907099ed4506fe0d39250aeb10b755ac6a04a0ad
Status: Downloaded newer image for nvcr.io/nvidia/pytorch:20.03-py3
 ---> 16c4987611fa
Step 2/14 : RUN apt update && apt install curl gnupg
 ---> Running in 6bf12c661c88
standard_init_linux.go:211: exec user process caused "exec format error" 
The command '/bin/sh -c apt update && apt install curl gnupg' returned a non-zero code: 1
```

I wonder how can I fix this error?
Thank you

BR,
Chieh 

## To Reproduce

Follow steps from the page of [instruction](https://github.com/NVIDIA/TRTorch/tree/master/notebooks#1-requirements).

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

- PyTorch Version: 1.15.0
- JetPack Version: 4.4
- How you installed PyTorch: from here
- Python version: 3.6
- CUDA version: 10.2
- GPU models and configuration: AGX jetson device
- TRT version default is 7.1.0.16 on JetPack 4.4
- bazel version: 3.4.0

**Comment by andi4191** [comment]
@chiehpower: Are you building the docker container on aarch64 platform?
Please note that the architecture is configured as amd64 in [Dockerfile.notebook](https://github.com/NVIDIA/TRTorch/blob/master/Dockerfile.notebook#L5) and you are running it on aarch64 platform.

**Comment by chiehpower** [comment]
> @chiehpower: Are you building the docker container on aarch64 platform?
> Please note that the architecture is configured as amd64 in [Dockerfile.notebook](https://github.com/NVIDIA/TRTorch/blob/master/Dockerfile.notebook#L5) and you are running it on aarch64 platform.

Hi @andi4191 ,

I see! I was trying to implement TRTorch by nvidia-docker on AGX device. 
Is there any method to use TRTorch by NGC on aarch64 platform currently?
I can run the TRT and guided from [nvidia:deepstream-l4t](https://ngc.nvidia.com/catalog/containers/nvidia:deepstream-l4t).
Could you provide some hints with me?
Thank you!

BR,
Chieh

**Comment by andi4191** [comment]
For building TRTorch on Jetson AGX you need libtorch which you can get at [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)

You can try basing your custom Dockerfile over NGC container to get libtorch and add the recipe for building TRTorch along with its dependencies altogether on aarch64 platform itself.

Contributions are most welcome.

**Comment by chiehpower** [comment]
> For building TRTorch on Jetson AGX you need libtorch which you can get at [NGC](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch)
> 
> You can try basing your custom Dockerfile over NGC container to get libtorch and add the recipe for building TRTorch along with its dependencies altogether on aarch64 platform itself.
> 
> Contributions are most welcome.

Got it!! 
Previously I was looking forward a container such as which included the TRTorch already that we don't need to particularly build again by ourselves, but unfortunately it is only for amd64. 

I think I might try to let it work on local first, because even now I still cannot import trtorch successfully... ( Ref: #132 ) 
Thanks for your advice and help.

Best regards,
Chieh

**Comment by chiehpower** [comment]
Close first. Feel free to re-open.
