### ISSUE TITLE
🐛 [Bug] support for aten::div(ITensor, IValue)

### ISSUE THREAD

**Issue by wcy116** [NVIDIA/TRTorch#145]
Pytorch supports the torch.div(Tensor, Number) op, while I can only find the converter aten::div(Tensor, Tensor). The converter doesn't work when self is ITensor and other IValue in div op.

INFO: [TRTorch Conversion Context] - Adding Layer %x0.1 : Tensor = aten::div(%x.2, %10) # prepare_sdk.py:37:0 (ctx.AddLayer)
DEBUG: [TRTorch Conversion Context] - Node input is an already converted tensor
DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/conversion/var/Var.cpp:98] Expected isITensor() to be true but got false
Requested ITensor from Var, however Var type is c10::IValue

**Comment by narendasan** [comment]
Are you able to share a version of the TorchScript file that can replicate this issue? Ideally what we would do is add a pass that freezes these Tensors beforehand vs doing type checking in every converter.

**Comment by wcy116** [comment]
I have solved the problem by following your advice. Thank you very much.

**Comment by yuezhuang1387** [comment]
> I have solved the problem by following your advice. Thank you very much.

Hi, how did you solve it? I also encountered the same error report
