### ISSUE TITLE
❓ [Question] How to convert at::tensor into nvinfer1::ITensor?

### ISSUE THREAD

**Issue by zhanjw** [NVIDIA/TRTorch#146]
## ❓ Question

how to convert at::tensor into nvinfer1::ITensor?

## What you have already tried

I tried to run resnet101 using trtorch, however, there was an error when compiling the graph.
As a result of my analysis

TRTorch/core/conversion/converters/impl/element_wise.cpp

```
"aten::div.Tensor(Tensor self, Tensor other) -> Tensor",
[](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
	// Should implement self / other
	auto self = args[0].ITensor();
	auto other = args[1].ITensor();
	auto div = add_elementwise(ctx, nvinfer1::ElementWiseOperation::kDIV, self, other, util::node_info(n));

	TRTORCH_CHECK(div, "Unable to create div layer from node: " << *n);

	div->setName(util::node_info(n).c_str());
	auto out = ctx->AssociateValueAndTensor(n->outputs()[0], div->getOutput(0));

	LOG_DEBUG("Output tensor shape: " << out->getDimensions());
	return true;
 }
```

self is the ITensor type
other is the IValue type

Thus, this program exits with an error in determining the type.

`auto other = args[1].ITensor();`

I know IValue can be unpacked into at::tensor, however add_elementwise requires nvinfer1::ITensor

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu
 - CUDA version: 10.2 with cudnn 8.0
 - GCC/G++: 7.5.0

**Comment by narendasan** [comment]
You can add a IConstant layer to freeze the `at::Tensor`. 

```cpp
            auto t = args[0].unwrapToTensor();
            auto t_weights = Weights(ctx, t);
            auto const_layer = ctx->net->addConstant(t_weights.shape, t_weights.data);
            auto const_tensor = const_layer->getOutput(0);
```

**Comment by narendasan** [comment]
This however seems like the issue is that there is some static value with should be frozen beforehand. Seems similar to #145

**Comment by zhanjw** [comment]
Sorry to bother you again, I've changed the code as the following.

```
                auto self = args[0].ITensor();
                decltype(self) other;
                if (args[1].isIValue()) {
                    auto t = args[1].unwrapToTensor();
                    auto t_weights = Weights(ctx, t);
                    auto const_layer = ctx->net->addConstant(t_weights.shape, t_weights.data);
                    other = const_layer->getOutput(0);
                }
                else {
                    other = args[1].ITensor();
                }
                auto div = add_elementwise(ctx, nvinfer1::ElementWiseOperation::kDIV, self, other, util::node_info(n));
```

And got this error.

> INFO: [TRTorch Conversion Context] - Adding Layer %x0.1 : Tensor = aten::div(%x.2, %10) # prepare_sdk.py:37:0 (ctx.AddLayer)
> DEBUG: [TRTorch Conversion Context] - Node input is an already converted tensor
> DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
> DEBUG: [TRTorch - Debug Build] - Weights: [1]
>     Number of input maps: 1
>     Number of output maps: 1
>     Element shape: [1]
> terminate called after throwing an instance of 'trtorch::Error'
>   what():  [enforce fail at core/conversion/converters/impl/element_wise.cpp:19] Expected util::volume(self_dims) == util::volume(other_dims) || util::volume(self_dims) == util::volume(other_dims) / other_batch to be true but got false
> Found inputs to elementwise operation do not have the same number of elements or is not broadcastable:
>   Found: self [3, 3, 224, 224] other [1]

I think the calculations this converter is trying to implement are
self=[s1, s2, s3, ... , sn]
other=[o1, o2, o3, ... , on]
result=self/other=[s1/o1, s2/o2, s3/o3, ... , sn/on]

And I want to get the following results
self=[s1, s2, s3, ... , sn]
other=[o]
result=self/other=[s1/o, s2/o, ... , sn/o]

So now the question is how do I broadcast a single scalar to the size (3,3,224,224)?

```
                    auto t = args[1].unwrapToTensor();
                    auto t_weights = Weights(ctx, t);
                    auto const_layer = ctx->net->addConstant(t_weights.shape, t_weights.data);
                    other_temp = const_layer->getOutput(0);

                    at::Tensor a = torch::ones(other_temp.sizes(), other_temp.dtype()) * other_temp[0];
```
Is that okay? Is there a way to do something similar to torch.expand or numpy.broadcast_to?
I'm new to c++ torchscript and still unfamiliar with it, thank you.

**Comment by zhanjw** [comment]
Hello, I have successfully solved this problem.
It seems that in my model the problem occurs not only in div, but also in sub, so I have added code in both.

```
                auto self = args[0].ITensor();
                decltype(self) other;
                if (args[1].isIValue()) {
                    auto other_tensor = args[1].unwrapToTensor();
                    nvinfer1::Dims selfDims = self->getDimensions();
                    std::cout<<selfDims.d[0]<<std::endl;
                    std::cout<<selfDims.d[1]<<std::endl;
                    std::cout<<selfDims.d[2]<<std::endl;
                    std::cout<<selfDims.d[3]<<std::endl;
                    auto t = at::ones({selfDims.d[0], selfDims.d[1], selfDims.d[2], selfDims.d[3]}, other_tensor.dtype()) * other_tensor[0];
                    auto t_weights = Weights(ctx, t);
                    auto const_layer = ctx->net->addConstant(t_weights.shape, t_weights.data);
                    other = const_layer->getOutput(0);
                }
                else {
                    other = args[1].ITensor();
                }
                //auto other = args[1].ITensor();
```

After solving that problem, a new one arose, one that felt a bit difficult to solve.

> DEBUG: [TRTorch - Debug Build] - Output tensor shape: [3, 3, 224, 224]
> INFO: [TRTorch Conversion Context] - Adding Layer %537 : Tensor = aten::sub(%x0.1, %16, %13) # prepare_sdk.py:38:0 (ctx.AddLayer)
> DEBUG: [TRTorch Conversion Context] - Node input is an already converted tensor
> DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
> DEBUG: [TRTorch Conversion Context] - Node input is a result of a previously evaluated value
> 3
> 3
> 224
> 224
> terminate called after throwing an instance of 'c10::Error'
>   what():  expected device cpu but got device cuda:0 (compute_types at /pytorch/aten/src/ATen/native/TensorIterator.cpp:246)
> frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f7314400536 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libc10.so)
> frame #1: at::TensorIterator::compute_types() + 0x17d4 (0x7f7351e5d514 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #2: at::TensorIterator::build() + 0x44 (0x7f7351e5f404 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #3: at::TensorIterator::binary_op(at::Tensor&, at::Tensor const&, at::Tensor const&, bool) + 0x146 (0x7f7351e5fab6 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #4: at::native::mul(at::Tensor const&, at::Tensor const&) + 0x3a (0x7f7351b7ebfa in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #5: <unknown function> + 0xf65148 (0x7f7315775148 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cuda.so)
> frame #6: <unknown function> + 0x10c2780 (0x7f73520e5780 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #7: <unknown function> + 0x2d2e279 (0x7f7353d51279 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #8: <unknown function> + 0x10c2780 (0x7f73520e5780 in /home/eric/Desktop/libtorch-video-classification/third_path/libtorch/lib/libtorch_cpu.so)
> frame #9: at::Tensor c10::KernelFunction::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&) const + 0x82 (0x7f736f20e7fe in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #10: at::Tensor c10::Dispatcher::callUnboxedWithDispatchKey<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, c10::DispatchKey, at::Tensor const&, at::Tensor const&) const + 0x9d (0x7f736f20e06d in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #11: at::Tensor c10::Dispatcher::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&>(c10::OperatorHandle const&, at::Tensor const&, at::Tensor const&) const + 0x9a (0x7f736f20d37e in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #12: at::Tensor c10::OperatorHandle::callUnboxed<at::Tensor, at::Tensor const&, at::Tensor const&>(at::Tensor const&, at::Tensor const&) const + 0x57 (0x7f736f20c4d5 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #13: at::Tensor::mul(at::Tensor const&) const + 0x9a (0x7f736f20a6bc in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #14: <unknown function> + 0x1b432e (0x7f736f21b32e in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #15: <unknown function> + 0x1b62b5 (0x7f736f21d2b5 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #16: <unknown function> + 0x1b98c6 (0x7f736f2208c6 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #17: <unknown function> + 0x1b8f41 (0x7f736f21ff41 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #18: <unknown function> + 0x1b85f1 (0x7f736f21f5f1 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #19: std::function<bool (trtorch::core::conversion::ConversionCtx*, torch::jit::Node const*, std::vector<trtorch::core::conversion::Var, std::allocator<trtorch::core::conversion::Var> >&)>::operator()(trtorch::core::conversion::ConversionCtx*, torch::jit::Node const*, std::vector<trtorch::core::conversion::Var, std::allocator<trtorch::core::conversion::Var> >&) const + 0x76 (0x7f736f1ee38e in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #20: trtorch::core::conversion::AddLayer(trtorch::core::conversion::ConversionCtx*, torch::jit::Node const*) + 0xd3f (0x7f736f1e84fd in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #21: trtorch::core::conversion::ConvertBlockToNetDef(trtorch::core::conversion::ConversionCtx*, torch::jit::Block const*, trtorch::core::conversion::ConversionInfo, std::map<torch::jit::Value*, at::Tensor, std::less<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, at::Tensor> > >&) + 0x4fe (0x7f736f1ebefb in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #22: trtorch::core::conversion::ConvertBlockToEngine(torch::jit::Block const*, trtorch::core::conversion::ConversionInfo, std::map<torch::jit::Value*, at::Tensor, std::less<torch::jit::Value*>, std::allocator<std::pair<torch::jit::Value* const, at::Tensor> > >&) + 0x98 (0x7f736f1ec345 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #23: trtorch::core::ConvertGraphToTRTEngine(torch::jit::Module const&, std::string, trtorch::core::ExtraInfo) + 0x217 (0x7f736f1ce413 in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #24: trtorch::core::CompileGraph(torch::jit::Module const&, trtorch::core::ExtraInfo) + 0x208 (0x7f736f1ce78a in ../../third_path/trtorch/lib/libtrtorch.so)
> frame #25: trtorch::CompileGraph(torch::jit::Module const&, trtorch::ExtraInfo) + 0x113 (0x7f736f1c3839 in ../../third_path/trtorch/lib/libtrtorch.so)

Do you have any ideas?

**Comment by zhanjw** [comment]
I added code to "aten::sub" and "aten::div" in trtorch/core/conversion/converters/impl/element_wise.cpp

```
            "aten::div.Tensor(Tensor self, Tensor other) -> Tensor",
            [](ConversionCtx* ctx, const torch::jit::Node* n, args& args) -> bool {
                // Should implement self / other
                auto self = args[0].ITensor();
                decltype(self) other;
                if (args[1].isIValue()) {
                    auto other_tensor = args[1].unwrapToTensor().to("cpu"); //Note that this must be loaded to the CPU, otherwise when other_tensor is on the GPU, the subsequent code will report an error and exit.

                    nvinfer1::Dims selfDims = self->getDimensions();
                    auto t = at::ones({selfDims.d[0], selfDims.d[1], selfDims.d[2], selfDims.d[3]}, other_tensor.dtype()) * other_tensor[0]; // Broadcast. Here you need to broadcast explicitly, otherwise an error will be reported because the size is different.

                    auto t_weights = Weights(ctx, t);
                    auto const_layer = ctx->net->addConstant(t_weights.shape, t_weights.data);
                    other = const_layer->getOutput(0); // Thanks for your help.
                }
                else {
                    other = args[1].ITensor();
                }
                //auto other = args[1].ITensor();
                auto div = add_elementwise(ctx, nvinfer1::ElementWiseOperation::kDIV, self, other, util::node_info(n));
                TRTORCH_CHECK(div, "Unable to create div layer from node: " << *n);
                div->setName(util::node_info(n).c_str());
                auto out = ctx->AssociateValueAndTensor(n->outputs()[0], div->getOutput(0));
                LOG_DEBUG("Output tensor shape: " << out->getDimensions());
                return true;
             }
```
             
Problem solved. Compile pt model passed. Hope this helps, thanks.
