### ISSUE TITLE
Add support for aten::narrow

### ISSUE THREAD

**Issue by xsacha** [NVIDIA/TRTorch#151]
aten::narrow
https://pytorch.org/docs/master/generated/torch.narrow.html

Can also be performed using Python indexing.
For eg: torch.narrow(tensor, 2, 100, 300) is the same as tensor[:,:,100:400,:]

**Comment by xsacha** [comment]
Still an issue. Not sure how to fix it but I assume it couldn't be too hard since python indexing works already and does the same thing.

**Comment by narendasan** [comment]
I think that you would do something similar to gather or select in TensorRT. Since PyTorch uses a different op it either needs a specific converter or a pass which can reduce it to some already supported operator

**Comment by xsacha** [comment]
So we can't just do whatever we do for torch.slice, for torch.narrow? It's the same instruction.

**Comment by narendasan** [comment]
cc @peri044
