### ISSUE TITLE
🐛 [Bug] Windows crash at runtime

### ISSUE THREAD

**Issue by xsacha** [NVIDIA/TRTorch#153]
##  Bug Description

I created a TRTorch 0.0.3 for Windows and have noticed it crashes at runtime when registering the operators.

Backtrace:
![image](https://user-images.githubusercontent.com/61218/87925825-33391080-cac4-11ea-9ba6-991fe3989059.png)

Schema:
`trt::execute_engine(Tensor[] inputs, __torch__.torch.classes.tensorrt.Engine engine) -> Tensor[]`

Function it dies in, while parsing schema:
https://github.com/pytorch/pytorch/blob/4a3aad354a14edb1337c6214c3d3870c136d5286/torch/csrc/jit/frontend/schema_type_parser.cpp#L307

## To Reproduce

1. Use Windows
2. Use my precompiled TRTorch
3. Link to TRTorch

Prebuilt is available in PR #152 or for debug library: 
[trtorch-0.0.3-debug.zip](https://github.com/NVIDIA/TRTorch/files/4947139/trtorch-0.0.3-debug.zip)

## Expected behavior

Runs

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6.0-rc3
 - CPU Architecture: x64
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): libtorch
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.7
 - CUDA version: 10.2
 - GPU models and configuration: RTX 2060
 - Any other relevant information:

**Comment by narendasan** [comment]
I am currently working required updates to TRTorch to be compatible with 1.6.0. There are some issues i have hit from using the 0.0.3 branch. Perhaps that is the root cause? When I compiled on windows I used the 1.5.1 official build from pytorch.org. Ill see if i can replicate once the update is complete.

**Comment by xsacha** [comment]
@narendasan Any update on the 1.6.0 compatibility? I guess that's what this bug is.

**Comment by narendasan** [comment]
I just wrapped up the update to 1.6.0, so I can start to take a look at this. Do you have a short example program that can replicate this issue? Right now what I see is that some of the example applications we have seem to be able to start up properly without hitting this issue.

**Comment by xsacha** [comment]
Every model I've tested seems to hit this issue. I couldn't find a way to not reproduce this.
