### ISSUE TITLE
🐛 [Bug] C++ Serialise produces a model that cannot be loaded

### ISSUE THREAD

**Issue by xsacha** [NVIDIA/TRTorch#167]
##  Bug Description

When I serialise a model in C++ using .save()
```
auto compile_settings = trtorch::ExtraInfo(dims);
compile_settings.op_precision = torch::kFloat;
m = trtorch::CompileGraph(m, compile_settings);
// Serialise for later
m.save(opt.string());
```
Then try to do torch::jit::load on this model, I get:

[enforce fail at ..\..\caffe2\serialize\inline_container.cc:209] . file not found: facespoof_grey_opt/constants.pkl

Note: It appears to work correctly when saved from Python.

## Expected behavior

Same as Python

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6.0
 - CPU Architecture: AMD64
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): libtorch
 - Build command you used (if compiling from source): N/A
 - Are you using local sources or building from archives: archives
 - Python version: N/A
 - CUDA version: 10.2
 - GPU models and configuration: RTX2060
 - Any other relevant information:

**Comment by narendasan** [comment]
Can you try unzipping the TRTorch compiled program and see if that constants.pkl file is there? Also do you notice similar behavior if you load and save the module without compiling with TRTorch?

**Comment by xsacha** [comment]
The compiled model has:
data.pkl (approx twice size of original model)
version (2 bytes)

**Comment by narendasan** [comment]
Are you able to run `test_serialization` in the test suite? 

To run the test first run `hub.py` in the `tests/modules` directory to download the test models. 
Then `bazel test //tests/modules:test_serialization --test_output=errors`

**Comment by xsacha** [comment]
Tried to build test and it failed here:
ore/conversion/conversionctx/ConversionCtx.h(7): fatal error C1083: Cannot open include file: 'torch/csrc/jit/ir/ir.h': No such file or directory

Will explore later

**Comment by xsacha** [comment]
Not stale. Still actively waiting for a solution.
