### ISSUE TITLE
✨[Feature] Automatically fallback operators unsupported by TensorRT to libtorch

### ISSUE THREAD

**Issue by uni19** [NVIDIA/TRTorch#170]
Do you have plane to support this feature like [TF-TRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#benefits)?

**Comment by narendasan** [comment]
Check this issue for more context and current workarounds https://github.com/NVIDIA/TRTorch/issues/79. Short answer is we are exploring the idea but it is not a high priority right now.
