### ISSUE TITLE
🐛 [Bug] UnicodeDecodeError running setup.py

### ISSUE THREAD

**Issue by mneilly** [NVIDIA/TRTorch#192]
##  Bug Description

Trying to run "python setup.py install" fails with a unicode error when reading README.md.

## To Reproduce

1. docker run --gpus=all -it nvcr.io/nvidia/tensorrt:20.03-py3 /bin/bash
2. (cd /usr/bin && wget -O bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.7.3/bazelisk-linux-amd64 && chmod +x bazel)
3. git clone https://github.com/NVIDIA/TRTorch.git
4. cd TRTorch/py
5. pip install -r requirements.txt
6. python setup.py install

The error follows:
> root@320583666d0c:/workspace/TRTorch/py# python setup.py install        
> Traceback (most recent call last):
>   File "setup.py", line 194, in <module>
>     long_description = fh.read()
>   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7349: ordinal not in range(128)

## Expected behavior

No unicode error

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - CPU Architecture: x86
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): python setup.py install
 - Are you using local sources or building from archives: local sources (git clone)
 - Python version: 3.6.9
 - CUDA version: 10.2.89
 - GPU models and configuration: gtx 970

## Additional context

The following appears to resolve the issue:

```
diff --git a/py/setup.py b/py/setup.py
index 53f85da..8344c0a 100644
--- a/py/setup.py
+++ b/py/setup.py
@@ -190,7 +190,7 @@ ext_modules = [
                             )
 ]
 
-with open("README.md", "r") as fh:
+with open("README.md", "r", encoding="utf-8") as fh:
     long_description = fh.read()
 
 setup(
```

**Comment by narendasan** [comment]
Thanks for catching this!
