### ISSUE TITLE
❓ [Question] How does max_batch_size work? 

### ISSUE THREAD

**Issue by ateraz** [NVIDIA/TRTorch#193]
## ❓ Question

How one should use `max_batch_size` compilation option? There's not a lot said about it on [documentation](https://nvidia.github.io/TRTorch/py_api/trtorch.html) apart of that it should greater than 0.

## What you have already tried

Here's the toy example I'm playing with:
```
import torch
import trtorch

torch.manual_seed(0)

size = (1, 1)
torch_model = torch.nn.Linear(*size)
script_model = torch.jit.script(torch_model.eval().cuda())
trt_model = trtorch.compile(script_model, {
    "input_shapes": [size],
    "op_precision": torch.half,
    "max_batch_size": 2
})

print("Single value:")
x1 = torch.rand(size).cuda()
print(torch_model(x1).tolist(), trt_model(x1.half()).tolist())

print("Batch:")
x2 = torch.rand((2, 1)).cuda()
print(torch_model(x2).tolist(), trt_model(x2.half()).tolist())
```
I'm expecting the output to be the same for both PyTorch and TRTorch models for both `x1` and `x2`. Here's the output I'm getting (notice the error message and missing second value from TRTorch model on the last line):
```
$ python test.py 
Single value:
[[0.53578120470047]] [[0.5357810258865356]]
Batch:
ERROR: [__torch__.torch.nn.modules.linear.Linear_trt_engine] - Parameter check failed at: engine.cpp::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
[[0.5354551076889038], [0.5341419577598572]] [[0.5354547500610352]]
```
I expected that setting `max_batch_size=2` would do the trick but apparently it does not.
## Environment
 - x86 CPU Architecture, 1660Ti GPU, Linux OS;
 - Python 3.8.6;
 - CUDA 10.1;
 - PyTorch 1.5.1, installed using pip;
 - TRTorch 0.0.3, installed using `pip install  https://github.com/NVIDIA/TRTorch/releases/download/v0.0.3/trtorch-0.0.3-cp38-cp38-linux_x86_64.whl`

**Comment by narendasan** [comment]
Max batch size is a legacy setting for TensorRT which is used to constrain the memory used during building. Now that we only use explicit batch sizes this setting doesn't do anything anymore and will be removed in a future version. Now the batch size is set via the input size. The first dimension in the input shape is considered the batch size. So for a CNN the dimension will be specified by NCHW where N is the batch size. When setting the input shape there are two options, static shape or dynamic shape. What you did was static shape so this means the TensorRT engine will expect every time you run the engine to be feed with exactly that shape tensor. Dynamic shape allows the engine to handle a range of input shapes and would be the way you approach your test case.

```python
import torch
import trtorch

torch.manual_seed(0)

torch_model = torch.nn.Linear(1, 1)
script_model = torch.jit.script(torch_model.eval().cuda())
trt_model = trtorch.compile(script_model, {
    "input_shapes": [{
        "min": (1,1),
        "opt": (2,1),
        "max": (2,1)
    }],
    "op_precision": torch.half,
})

print("Single value:")
x1 = torch.rand((1,1)).cuda()
print(torch_model(x1).tolist(), trt_model(x1.half()).tolist())

print("Batch:")
x2 = torch.rand((2, 1)).cuda()
print(torch_model(x2).tolist(), trt_model(x2.half()).tolist())
``` 

So in this example I set the min size to the single batch size and the max to the 2 batch size. Opt is the target size so the most common batch size, this will be the size that will be optimized.

**Comment by ateraz** [comment]
Thank you for detailed response. I confirm that your example works. I've tried to use dynamic shape before for more complex networks and encountered different bug. Probably that's why I did not try dynamic shape here.
Anyway, I'll close this one and open a different issue with steps to reproduce later.
