### ISSUE TITLE
✨[Feature] PyTorch 1.7 Update 

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#207]
Update the compiler dependency to PyTorch 1.7 and make sure all features work.

**Comment by bpfliegel** [comment]
Don't forget to add #include "torch/csrc/jit/passes/remove_mutation.h" in lowering.cpp :)

**Comment by bpfliegel** [comment]
I tested with 20.10 level dockers, with latest PyTorch sources and CUDA 11.1 updated workspace, runs well.

**Comment by cbasavaraj** [comment]
Hi, do you have an idea by when PyTorch 1.8 will be supported? detectron2's TorchScript export script says 1.8 is needed. I used the nightly build and did the export. But unable to load the saved .ts model, even in 1.8 itself (This I think is a PyTorch / d2 issues, not yours). So I wanted to do the scripting, and without saving to disk, compile it using TRTorch. Which in turn implies that TRTorch will also need to support 1.8. Thanks

**Comment by narendasan** [comment]
PyTorch 1.8 support will come after PyTorch 1.8 is released.

**Comment by cbasavaraj** [comment]
Fair enough, thanks.
