### ISSUE TITLE
✨[Feature] Please support aten::instance_norm

### ISSUE THREAD

**Issue by bpfliegel** [NVIDIA/TRTorch#210]
**Is your feature request related to a problem? Please describe.**
I'm struggling to convert a PyTorch model.

**Describe the solution you'd like**
To have this operator supported.

**Describe alternatives you've considered**
To implement it myself, however I'm yet there!

**Additional context**
Thanks for considering!

**Comment by peri044** [comment]
There's no native TensorRT op for instance norm. There is an open sourced plugin implementation [https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin](https://github.com/NVIDIA/TensorRT/tree/master/plugin/instanceNormalizationPlugin). Probably you can wrap this and add a converter which calls the plugin, similar to interpolate plugin example.

**Comment by narendasan** [comment]
We already have some plugin based converters in the library for reference on how to integrate.
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.h
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp

**Comment by bpfliegel** [comment]
I get the idea, thanks guys. I will look for alternatives - would do if I would have better knowledge on the internals and more time!
Thanks a lot again, Balint
