### ISSUE TITLE
While not compile\link any trtorch namespace member a not support for cuda devices runtime exception is rasied

### ISSUE THREAD

**Issue by OronG13** [NVIDIA/TRTorch#227]
##  Bug Description

In case my code doesn't include any usage of trtorch namespace types or methods which means that my application doesn't include any activation or usage of any member of the trtorch namespace the following is happened:

- torch::cuda::device_count return 0

-  torch::cuda::is_available return false

- torch::cuda::cudnn_is_available return false

- the torch::jit::load operation raise the following runtime exception:

`PyTorch is not linked with support for cuda devices
Exception raised from getDeviceGuardImpl at ../c10/core/impl/DeviceGuardImplInterface.h:216 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xa0 (0x7fa256e9a8 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xb69334 (0x7fa310c334 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #2: at::native::to(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool, c10::optional<c10::MemoryFormat>) + 0x210 (0x7fa310aa78 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0xeec714 (0x7fa348f714 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x1e345fc (0x7fa43d75fc in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0xf37524 (0x7fa34da524 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #6: at::Tensor::to(c10::Device, c10::ScalarType, bool, bool, c10::optional<c10::MemoryFormat>) const + 0x154 (0x7fa356420c in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x22dfd84 (0x7fa4882d84 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::jit::Module::to_impl(c10::optional<c10::Device> const&, c10::optional<c10::ScalarType> const&, bool) + 0x328 (0x7fa4884508 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::jit::Module::to(c10::Device, bool) + 0x44 (0x7fa48852b4 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x4594 (0x5580d83594 in ./TRTorchTester)
frame #11: __libc_start_main + 0xe0 (0x7fa220a6e0 in /lib/aarch64-linux-gnu/libc.so.6)
frame #12: <unknown function> + 0x49d0 (0x5580d839d0 in ./TRTorchTester)`

## To Reproduce

1.Make the LeNet module exactly as described in the TRTorch getting started:
[https://nvidia.github.io/TRTorch/tutorials/getting_started.html](url)
1.make the LeNet.pt using torch.jit.script
1.Create an application based on the following cpp code:
torch::jit::Module module;

	try
	{
		bool isCudaAvailable = torch::cuda::is_available();

		std::size_t devicesCount = torch::cuda::device_count();
		std::cout << "CUDA devices count - " << devicesCount << '\n';
		
		if (isCudaAvailable)
			std::cout << "CUDA available" << '\n';
		else
			std::cout << "CUDA NOT available" << '\n';

		bool isCudnnAvailable = torch::cuda::cudnn_is_available();

		if (isCudnnAvailable)
			std::cout << "CUDNN available" << '\n';
		else
			std::cout << "CUDNN NOT available" << '\n';
		
		// Deserialize the ScriptModule from a file using torch::jit::load().
		module = torch::jit::load("../../../../Source/Applications/TRTorchTester/Input/lenet_scripted.pt");

		module.to(at::kCUDA);
		module.eval();

		auto in = torch::randn({ 1, 1, 32, 32 }, { torch::kCUDA });
		auto trt_mod = trtorch::CompileGraph(module, std::vector<trtorch::CompileSpec::InputRange>{ {in.sizes()}});
		auto out = trt_mod.forward({ in });
	}
	catch (const c10::Error & e) {
		std::cerr << "torch error - \n"<< e.what() << '\n';
		return -1;
	}

1. This code is OK which means that the runtime exception isn't raised and I'm getting the following prints:
CUDA devices count - 1
CUDA available
CUDNN available

1. If I only masked the following lines:
`auto in = torch::randn({ 1, 1, 32, 32 }, { torch::kCUDA });
		auto trt_mod = trtorch::CompileGraph(module, std::vector<trtorch::CompileSpec::InputRange>{ {in.sizes()}});
		auto out = trt_mod.forward({ in });`

(To emphasize, I didn't change the build properties at all which means that I'm still compile and link with the same declarations)

The above mentioned runtime exception is rasied and the prints are:
CUDA devices count - 0
CUDA NOT available
CUDNN NOT available

## Expected behavior

To get the same prints as I got with the full code and not to get any runtime exception of unavailability PyTorch CUDA.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6
 - CPU Architecture: Jetson Xavier AGX
 - OS (e.g., Linux): Linux 18.04 - JetPack 4.4
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip3
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: Local sources
 - Python version: 3.6.9
 - CUDA version: 10.2
 - GPU models and configuration: Jetson Xavier AGX
 - Any other relevant information: JetPack 4.4

**Comment by narendasan** [comment]
@andi4191 can you take a look at this?

**Comment by andi4191** [comment]
@OronG13: I looked into this problem and came across an already reported [issue](https://discuss.pytorch.org/t/error-pytorch-is-not-linked-with-support-for-cuda-devices/103807).

I tried using the following compilation flag as suggested on the link and it seems to run fine after that.
`-Wl,--no-as-needed -ltorch_cuda -Wl,--as-needed`

Can you try this and let us know if it works for you?

**Comment by OronG13** [comment]
Hello,
It works well and the problem is solved - Thanks!

I added the following command:

'set (CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--no-as-needed -ltorch_cuda -Wl,--as-needed")`

Now I'm getting the following report:
CUDA devices count - 1
CUDA available
CUDNN available

Without using this linker flags line it come back to report that they (CYDA & CUDNN) are not available when no trtorch namespace is used.
