### ISSUE TITLE
Getting started lenet module loading operation raise an error

### ISSUE THREAD

**Issue by OronG13** [NVIDIA/TRTorch#228]
##  Bug Description

While activate the torch::jit::load operation on the TRTorch getting started lenet module which saved exactly according to the getting started instructions:
[https://nvidia.github.io/TRTorch/tutorials/getting_started.html](url)

The following error is reported:
ERROR: [TRTorch Conversion Context] - Parameter check failed at: ../builder/Layers.h::setStrideNd::321, condition: ((stride.nbDims == 2 || stride.nbDims == 3) && allDimsGt(stride, 0) && allDimsLtEq(stride, 100000))

It happens also for TRTorch Release and Debug
[WithTRTorchDebugTraced.txt](https://github.com/NVIDIA/TRTorch/files/5558200/WithTRTorchDebugTraced.txt)
[WithTRTorchReleaseTraced.txt](https://github.com/NVIDIA/TRTorch/files/5558201/WithTRTorchReleaseTraced.txt)

## To Reproduce

1.Perform all TRTorch getting started instructions described above

The code is exactly as provided in the Getting started guide

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6
 - CPU Architecture: Jetson Xavier AGX
 - OS (e.g., Linux):JetPack 4.4
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):pip3
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: Local
 - Python version:3.6.9
 - CUDA version:10.2
 - GPU models and configuration: Jetson Xavier AGX
 - Any other relevant information: JetPack 4.4

**Comment by narendasan** [comment]
Thanks for catching this. Seems like PyTorch doesn't provide default stride explicitly. It shouldn't effect the operation of the compiler since TensorRT falls back to kernel size as the default but this patch adds it explicitly to suppress the error #233 .

**Comment by OronG13** [comment]
Hello @narendasan,
Just want to say thanks.

When I made the update described in the error [https://github.com/NVIDIA/TRTorch/pull/233](url) and rebuild again the TRTorch the Lenet module started to work properly for both Debug and Release.
