### ISSUE TITLE
How do you activate trtorch::CompileGraph with multi inputs?

### ISSUE THREAD

**Issue by OronG13** [NVIDIA/TRTorch#232]
## ❓ Question

Can you provide an example of using more than one input please?

## What you have already tried

For example I tried to do the following:
` auto Input1= torch::randn({ 4, 24, 64, 64 }, { torch::kCUDA });
  auto Input2= torch::randn({ 1, 24, 1, 1 }, { torch::kCUDA });

std::vector<trtorch::CompileSpec::InputRange> inputRanges;

inputRanges.push_back(Input1.sizes());
inputRanges.push_back(Input2.sizes());

auto trt_mod = trtorch::CompileGraph(module, inputRanges);

`

A std::out_of_range exception was raised.

I can't be sure that the exception root cause related to the multi inputs that I used but for now I have no other suspicious.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6
 - CPU Architecture: Jetson Xavier AGX
 - OS (e.g., Linux): JetPack 4.4
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip3
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives: Local
 - Python version: 3.6.9
 - CUDA version: 10.2
 - GPU models and configuration: Jetson Xavier AGX
 - Any other relevant information: JetPack 4.4

**Comment by peri044** [comment]
An example on how to use multi inputs with CompileGraph can be found here 
[https://github.com/NVIDIA/TRTorch/blob/b93627ecc7bb7123d2e32aff9d762dd0e6bc3166/tests/modules/test_multiple_registered_engines.cpp#L44](https://github.com/NVIDIA/TRTorch/blob/b93627ecc7bb7123d2e32aff9d762dd0e6bc3166/tests/modules/test_multiple_registered_engines.cpp#L44)

**Comment by OronG13** [comment]
Thanks!
