### ISSUE TITLE
❓ [Question] How to solve aten::floor converter not found?

### ISSUE THREAD

**Issue by heatedcheese** [NVIDIA/TRTorch#240]
## ❓ Question

How to solve aten::floor converter not found?

## What you have already tried

 I am trying to convert a jit trace of a Fast SCNN network into TensorRT.  I've confirmed that the trace was created in python3.6 using PyTorch 1.6.0.  When printing the trace graph I do not even see the aten::floor operator.  I also cannot locate a torch.floor operator in the original PyTorch model structure so I'm not sure what is even calling this operator?  Here is the resulting error:
```
RuntimeError: [enforce fail at core/conversion/conversion.cpp:112] Expected converter to be true but got false
Unable to convert node: %376 : Tensor = aten::floor(%324) # /home/nmonhollen/tensorrt/venv/lib/python3.6/site-packages/torch/nn/functional.py:3010:0 (conversion.AddLayer)
Schema: aten::floor.int(int a) -> (int)
Converter for aten::floor requested, but no such converter was found.
If you need a converter for this operator, you can try implementing one yourself
or request a converter: https://www.github.com/NVIDIA/TRTorch/issues
```

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.6.0
 - CPU Architecture: x86-64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): 
 - Are you using local sources or building from archives: local sources (cuDNN=7.6.5, TensorRT=7.0.0.11)
 - Python version: 3.6.9
 - CUDA version: 10.2
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by narendasan** [comment]
I think this might be a numerical operation that gets injected by one of the lowering passes. We need to support via an evaluator. We already support `float` to `int` floor but not `int` to `int` floor, I think it should be pretty straight forward to do so.

**Comment by heatedcheese** [comment]
bump
