### ISSUE TITLE
❓ [Question] Has anyone exported detectron2?

### ISSUE THREAD

**Issue by cbasavaraj** [NVIDIA/TRTorch#241]
## ❓ Question

Hi, has anyone successfully exported detectron2 using TRTorch? Ideally the whole network from input list of images to output Instances. But I guess even just the backbone and other time consuming operations like RoIAlign can be useful.

I am yet to try myself, but found nothing in the Issues, so just checking. Thanks

**Comment by batrlatom** [comment]
This would be great since detectron team is veery resistent to tensorrt I think :+)
