### ISSUE TITLE
↔ [Converter] Add support for my_op in TRTorch

### ISSUE THREAD

**Issue by ramosmy** [NVIDIA/TRTorch#246]
##
aten:slice

- **Function Schema**: aten::slice.Tensor(Tensor(a) self, int dim=0, int start=0, int end=9223372036854775807, int step=1) -> (Tensor(a))

- **Original PyTorch API**: 1.6.0

- **Relevant TensorRT Documentation**: 0.1.0

**Comment by narendasan** [comment]
@peri044 Don't we already support slice in master at least?

**Comment by peri044** [comment]
We do support it in master. [https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/select.cpp#L143](url)
@ramosmy Did you face any unsupported converter issue with slice op? Can you post your error ?
