### ISSUE TITLE
failed build trtorch

### ISSUE THREAD

**Issue by pribadihcr** [NVIDIA/TRTorch#248]
Hi,

when run bazel build //:libtrtorch -c opt I got the following error:

no such package '@platforms//os': The repository '@platforms' could not be resolved and referenced by '//:windows'

**Comment by pribadihcr** [comment]
how to build it in ubuntu platform?

**Comment by narendasan** [comment]
Can you tell us more about your system configuration? especially what version of bazel you are using?

**Comment by pribadihcr** [comment]
sorry I was using older bazel version than 3..3.1. Its work now, but raise a new error:

core/conversion/converters/impl/conv_deconv.cpp: In lambda function:
core/conversion/converters/impl/conv_deconv.cpp:54:33: error: 'class nvinfer1::Dims' has no member named 'begin'
         for (auto it = dilation.begin(); it != dilation.end(); ++it) {
                                 ^~~~~
core/conversion/converters/impl/conv_deconv.cpp:54:57: error: 'class nvinfer1::Dims' has no member named 'end'
         for (auto it = dilation.begin(); it != dilation.end(); ++it) {
                                                         ^~~
Target //:libtrtorch failed to build

**Comment by peri044** [comment]
@pribadihcr Which TRT version are you using ? TRT 7.2 ?
Also a simple fix for this would be to replace this[ snippet of code](https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/conv_deconv.cpp#L54-L55) with 
```
for (int idx = 0; idx < dilation.nbDims; idx++) {
      TRTORCH_CHECK(dilation.d[idx] == 1, "for deconv with dilation > 1, require TensorRT version >= 7.1");
}
```
You need to recompile TRTorch with this.

**Comment by pribadihcr** [comment]
oh yes TRT 7.2. Thanks @peri044, its work now.
