### ISSUE TITLE
↔ [Converter] Add support for aten::grid_sampler in TRTorch

### ISSUE THREAD

**Issue by zccyman** [NVIDIA/TRTorch#262]
##

- **Function Schema**: aten::grid_sampler(Tensor input, Tensor grid, int interpolation_mode, int padding_mode, bool align_corners) -> (Tensor)

- **Original PyTorch API**: https://pytorch.org/docs/stable/nn.functional.html?highlight=grid_sample#torch.nn.functional.grid_sample

**Comment by peri044** [comment]
There's no native op in TensorRT which supports this. You would have to implement the plugin and integrate with TRTorch.
Some useful resources 
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/plugins/interpolate_plugin.h
- https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp

Let us know if you have any issues while integrating.

**Comment by vogoriachko** [comment]
Is any updates ?
