### ISSUE TITLE
✨[Feature] CMake support 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TRTorch#263]
Hi, I would like to appreciate this awesome work!  For those unfamiliar with the bazel (like me), I add the `CMakeLists.txt` and modify the `py/setup.py` to support compiling TRTorch via CMake.  See : 
https://github.com/JosephChenHub/TRTorch/tree/torch-1.6

**Comment by narendasan** [comment]
Hi, Thats pretty cool! I am going to make a note of this in the discussions section of the repo (https://github.com/NVIDIA/TRTorch/discussions/265) and close this issue (does not seem like there is an actual feature request here though correct me if I am wrong).
