### ISSUE TITLE
↔ [Converter] Add support for clamp in TRTorch

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#274]
## aten::clamp

- **Function Schema**:

- [ ] `aten::clamp_min(Tensor   self, Scalar min) -> (Tensor)`
- [ ] `aten::clamp_max(Tensor   self, Scalar max) -> (Tensor)`
- [ ] `aten::clamp(Tensor   self, Scalar min, Scalar max) -> (Tensor)`

- **Original PyTorch API**:

https://pytorch.org/docs/stable/generated/torch.clamp.html?highlight=clamp#torch.clamp

- **Relevant TensorRT Documentation**:

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html#iactivationlayer

**Comment by peri044** [comment]
Support added in https://github.com/NVIDIA/TRTorch/pull/293
