### ISSUE TITLE
↔ [Converter] Add support for aten::upsample_nearest2d.vec in TRTorch

### ISSUE THREAD

**Issue by james77777778** [NVIDIA/TRTorch#290]
## aten::upsample_nearest2d

- **Function Schema**:
`Schema: aten::upsample_nearest2d.vec(Tensor input, int[]? output_size, float[]? scale_factors) -> (Tensor)`

- **Original PyTorch API**:
Not sure where it is

- **Relevant TensorRT Documentation**:

## Alternatives
I think there is already a similar implementation 
`aten::upsample_nearest2d(Tensor self, int[2] output_size, float? scales_h=None, float? scales_w=None) -> (Tensor)`

maybe a small modification can solve this

## Additional context
I try to convert a yolov5 with TRTorch
[https://github.com/ultralytics/yolov5](https://github.com/ultralytics/yolov5)
I know there is another solution
[https://github.com/wang-xinyu/tensorrtx](https://github.com/wang-xinyu/tensorrtx)
but I want to practice TRTorch and further convert more complicated model...

I use the `models/export.py` provided by ultralytics's repo to convert yolo5s to `yolo5s.torchscript.pt` and then convert it as following:
```python
# load model
traced_model = torch.jit.load("yolov5s.torchscript.pt", map_location=torch.device("cpu"))
traced_model = traced_model.to(device)
traced_model = traced_model.eval()

# convert to TRTorch
trt_model_fp32 = trtorch.compile(traced_model, {
    "input_shapes": [(batch_size, 3, 416, 416)],
    "op_precision": torch.float32,  # Run with FP32
    "workspace_size": 1 << 20
})
```

The error message:
```bash
RuntimeError: [enforce fail at core/conversion/conversion.cpp:110] Expected converter to be true but got false
Unable to convert node: %282 : Tensor = aten::upsample_nearest2d(%input.31, %105, %106) # /home/xxxxxxxxxx/venv/lib/python3.6/site-packages/torch/nn/functional.py:3132:0 (conversion.AddLayer)
Schema: aten::upsample_nearest2d.vec(Tensor input, int[]? output_size, float[]? scale_factors) -> (Tensor)
Converter for aten::upsample_nearest2d requested, but no such converter was found.
If you need a converter for this operator, you can try implementing one yourself
or request a converter: https://www.github.com/NVIDIA/TRTorch/issues
```

**Comment by narendasan** [comment]
Are you able to trace this back to a specific pytorch api? It would make it easier to figure out if the schema changed or if this is a different variant of upsample nearest

**Comment by james77777778** [comment]
Environment (built from docker)
- python3.6
- pytorch 1.7.0a0+7036e91
- trtorch 0.2.0a0

I figure out the pytorch api (`F.interpolate`) and the code to reproduce is as following:
```python3
import torch
import torch.nn as nn
import torch.nn.functional as F
import trtorch


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 3, kernel_size=3, stride=2, padding=1)

    def forward(self, x):
        x1 = self.conv(x)
        x1 = F.interpolate(x1, size=(x.shape[2], x.shape[3]), mode="nearest")
        x = x1 + x
        return x


if __name__ == '__main__':
    device = torch.device("cuda")
    net = Net().to(device)
    net = net.eval()
    dummy_input = torch.randn(1, 3, 64, 64).to(device)
    traced_net = torch.jit.trace(net, dummy_input)
    trt_net = trtorch.compile(traced_net, {
        "input_shapes": [(1, 3, 64, 64)],
        "op_precision": torch.float32,  # Run with FP32
        "workspace_size": 1 << 20
    })
```

The error also happens when the mode is set to `"bilinear"` and `"bicubic"` in `F.interpolate`.

Furthermore, when I want to replace `F.interpolate` with `nn.ConvTranspose2d`, I found that the `output_padding` parameter in trtorch is not consistent with pytorch. The size of feature map is not the same.
