### ISSUE TITLE
Python Library error after painful compilation.

### ISSUE THREAD

**Issue by rafale77** [NVIDIA/TRTorch#294]
## ❓ Question

After very painfully building the repo from source due to a lot of strangely hardcoded paths to libraries and include which had me modify both the setup.py and the WORKSPACE, I have successfully completed the compilation using bazel. However when I try to use the python extension, I get the following error upon import of the library:

```
    import trtorch
  File "/home/user/.local/lib/python3.8/site-packages/trtorch/__init__.py", line 11, in <module>
    from trtorch._compiler import *
  File "/home/user/.local/lib/python3.8/site-packages/trtorch/_compiler.py", line 5, in <module>
    import trtorch._C
ImportError: /home/anhman/.local/lib/python3.8/site-packages/trtorch/lib/libtrtorch.so: undefined symbol: _ZN2at11show_configB5cxx11Ev
```

## What you have already tried

The last time I have seen something similar, it was due to attempts of running a compiled binary under a different version of pytorch than the one it was compiled with. It's not the case here as I compiles with 1.7.1.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.7.1-cu110
 - CPU Architecture: x64
 - OS (e.g., Linux): Ubuntu20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): bazel build //:libtrtorch --compilation_mode opt and then python3 setup.py install.
 - Are you using local sources or building from archives: source
 - Python version: 3.8.7
 - CUDA version: 11.2
 - GPU models and configuration: RTX 3070
 - Any other relevant information: TensorRT 7.2.2.3 and cudnn 8.1

**Comment by narendasan** [comment]
Usually this error occurs when the Python API was compiled using the wrong C++ ABI. I would try doing a `bazel clean` then directly using `python3 setup.py install` without the intermediate `bazel build` step

**Comment by rafale77** [comment]
I just did this an now its erroring out one line sooner:
```
    from trtorch._version import __version__
ModuleNotFoundError: No module named 'trtorch._version'
```

**Comment by narendasan** [comment]
for future notice TensorRT must be in the LD_LIBRARY_PATH

**Comment by developer0hye** [comment]
When I tried to run "python setup.py install" two times, this problem is solved.
But I don't know what problem is.

**Comment by developer0hye** [comment]
@rafale77 How do you solve it?

**Comment by rafale77** [comment]
It can get a bit complicated depending on your installation. I thought you fixed your problem did you not? Where are you stuck? The key is to get the compiler to find all the files it is looking for either by placing them where it is expecting them or by telling it where they are. Adding tensorRT to the LD_LIBRARY_PATH and to the include path helps but it isn't suffiscient. The repo seems to be made to compile in a container which is not what I am using.
