### ISSUE TITLE
❓ [Question] Is there a way to do multithreaded half-precision compilation?

### ISSUE THREAD

**Issue by SakodaShintaro** [NVIDIA/TRTorch#326]
## ❓ Question

I want to compile a Torch script in a different thread than the main thread in a C++ program. However, doing so with half precision for large networks will result in a Segmentation fault.

Here's a program that extracts what I want to do:
https://github.com/SakodaShintaro/trtorch-test/blob/master/main.cpp

```cpp
#include <torch/script.h>
#include <trtorch/trtorch.h>
using namespace std;

void compile(bool fp16) {
  constexpr int64_t INPUT_CHANNEL_NUM = 256;
  constexpr int64_t WIDTH = 32;
  torch::jit::Module module = torch::jit::load("model.ts");
  if (fp16) {
    module.to(torch::kCUDA, torch::kHalf);
  } else {
    module.to(torch::kCUDA);
  }
  module.eval();

  std::vector<int64_t> in_sizes = {1, INPUT_CHANNEL_NUM, WIDTH, WIDTH};
  trtorch::CompileSpec::InputRange range(in_sizes);
  trtorch::CompileSpec info({range});
  if (fp16) {
    info.op_precision = torch::kHalf;
  }
  module = trtorch::CompileGraph(module, info);
}

int main() {
  // fp32, this thread -> OK
  compile(false);
  cout << "fp32, this thread -> finish" << endl;

  // fp32, another thread -> OK
  std::thread thread0([]() { compile(false); });
  thread0.join();
  cout << "fp32, another thread -> finish" << endl;

  // fp16, this thread -> OK
  compile(true);
  cout << "fp16, this thread -> finish" << endl;

  // fp16, another thread -> NG
  std::thread thread1([]() { compile(true); });
  thread1.join();
  cout << "fp16, another thread -> finish" << endl;
}
```

 result

```
fp32, this thread -> finish
fp32, another thread -> finish
fp16, this thread -> finish
Segmentation fault (core dumped)
```

 Is there anything wrong with my code?

## Environment
 I used a Dockerfile I made.
https://github.com/SakodaShintaro/trtorch-test/blob/master/docker/Dockerfile

If I create a container with this image and execute `./Test`, a Segmentation fault will occur on the 4th line.

In `trtorch-test/docker`,

```
docker build -t trtorch_test_image .
docker run --gpus all -it --name trtorch_test_container trtorch_test_image:latest bash
./Test
```

I sometimes succeed in it, so try it a few times if you want to reproduce it.

 - PyTorch Version (e.g., 1.0): 1.7
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu 20.04 (on Docker)
 - Build command you used (if compiling from source): bazel build //:libtrtorch --compilation_mode opt
 - CUDA version: 11.0
 - GPU models and configuration: RTX 2080ti
 - Nvidia driver version : 460

**Comment by SakodaShintaro** [comment]
When I put a print statement and checked it, I found that a Segmentation Fault was occurring on the next line.
https://github.com/NVIDIA/TRTorch/blob/b93627ecc7bb7123d2e32aff9d762dd0e6bc3166/core/conversion/converters/Weights.cpp#L85

At fp16, since it is HalfType here, it may be the cause of the error that the area is acquired by `sizeof(float)`. I'm not sure why the Segumentation Fault occurs only in another thread ...

**Comment by narendasan** [comment]
@andi4191 or @peri044 Do you remember for FP16 in TensorRT if the weights should be in FP16/can be in FP16? Input tensors definitely do but I cant remember if this is something TensorRT can handle or if it expects weights in FP32.

**Comment by narendasan** [comment]
> When I put a print statement and checked it, I found that a Segmentation Fault was occurring on the next line.
> https://github.com/NVIDIA/TRTorch/blob/b93627ecc7bb7123d2e32aff9d762dd0e6bc3166/core/conversion/converters/Weights.cpp#L85
> 
> At fp16, since it is HalfType here, it may be the cause of the error that the area is acquired by `sizeof(float)`. I'm not sure why the Segumentation Fault occurs only in another thread ...

If I had to guess, it might have to do with how PyTorch does memory management but thats a stab in the dark. But this certainly enlightens the issue. I believe @andi4191 was able to replicate the issue at least occasionally, he can probably comment more on his findings.

**Comment by andi4191** [comment]
@narendasan: TensorRT can accept FP32 weights for FP16 precision. It automatically converts it:
https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#mixed_precision

Input bindings are expected to be of Half data type. 
https://github.com/NVIDIA/TensorRT/blob/master/samples/common/buffers.h#L267

@SakodaShintaro: I managed to reproduce the issue 1/5 occurrences. It runs fine if I run with gdb.
I am still investigating this.

**Comment by SakodaShintaro** [comment]
It works well in my environment. Thank you very much!
