### ISSUE TITLE
❓ [Question] Why bazel is not able to find libcudart-xxxxxxx.so.11.0? 

### ISSUE THREAD

**Issue by federicohml** [NVIDIA/TRTorch#337]
## ❓ Question

I cloned TRTorch repo and try to play with it with a sample code. I created a folder for this playground in the root path (next to WORKSPACE), add the corresponding `BUILD` and `cpp` files. However when executing `bazel build //adv_test:adv_torchscript --distdir third_party/dist_dir/x86_64-linux-gnu/` I get the following error `execroot/TRTorch/bazel-out/k8-fastbuild/bin/adv_test/adv_torchscript: error while loading shared libraries: libcudart-3f3c6934.so.11.0: cannot open shared object file: No such file or directory`

The BUILD file looks like

```
cc_binary(
    name = "adv_torchscript",
    srcs = ["adv_torchscript.cc"],
    deps = [
        "@cuda",
        "@libtorch",
        "@libtorch//:caffe2",
    ],
)
````
The cpp file looks like
````
#include <torch/script.h>
// #include <trtorch/trtorch.h>

// #include <chrono>
#include <iostream>
#include <string>

// https://gist.github.com/zeryx/526dbc05479e166ca7d512a670e6b82d
// https://github.com/pytorch/vision/issues/2691

int main(int argc, char** argv) {
  const std::string model_file = "./my_net_torch_script.pt";
  const std::string img_file = "./test_img.jpg";
  const float num_iterations = 1000.F;

  bool use_gpu = false;
  if (argc == 2) {
    use_gpu = std::atoi(argv[1]) ? true : false;
  }

  std::cout << "Device set to " << ((use_gpu) ? "GPU" : "CPU") << std::endl;

  std::cout << "Loading TorchScript Model";
  torch::jit::script::Module ts_module;
  if (use_gpu) {
    ts_module = torch::jit::load(model_file, torch::kCUDA);
  } else {
    ts_module = torch::jit::load(model_file);
  }
  std::cout << " ... OK" << std::endl;
  return 0;
}
````

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0):
 - CPU Architecture: amd64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):
 - Build command you used (if compiling from source): bazel build //adv_test:adv_torchscript --distdir third_party/dist_dir/x86_64-linux-gnu/
 - Are you using local sources or building from archives: archives
 - Python version: 3.8
 - CUDA version: 11.2
 - GPU models and configuration: GTX 1050
 - Any other relevant information: I updated the relevant parts of WORKSPACE to use the latest and greatest of CUDNN and TensorRT, i.e. URL and sha256sum.

**Comment by federicohml** [comment]
Same problem occurs when trying to build your executable `bazel run //cpp/trtorchc:trtorchc  --jobs=3 --distdir third_party/dist_dir/x86_64-linux-gnu/`

**Comment by federicohml** [comment]
I can confirm the same happens with the repo unmodified and CUDA 11.0

**Comment by narendasan** [comment]
With `bazel run` you need to make sure that you have all the libraries (libtorch, TRT, cuDNN) in your `LD_LIBRARY_PATH`. Bazel doesnt do this for you. I use something like `export LD_LIBRARY_PATH=$(pwd)/bazel-TRTorch/external/libtorch/lib/:$(pwd)/bazel-TRTorch/external/cudnn/lib64/:$(pwd)/bazel-TRTorch/external/tensorrt/lib/:/usr/local/cuda/lib64/:$LD_LIBRARY_PATH`

**Comment by federicohml** [comment]
> With `bazel run` you need to make sure that you have all the libraries (libtorch, TRT, cuDNN) in your `LD_LIBRARY_PATH`. Bazel doesnt do this for you. I use something like `export LD_LIBRARY_PATH=$(pwd)/bazel-TRTorch/external/libtorch/lib/:$(pwd)/bazel-TRTorch/external/cudnn/lib64/:$(pwd)/bazel-TRTorch/external/tensorrt/lib/:/usr/local/cuda/lib64/:$LD_LIBRARY_PATH`

@narendasan thank you very much, this was very helpful.
