### ISSUE TITLE
❓ [Question] What is the correct way to create a trtorch::CompileSpec for a single input? 

### ISSUE THREAD

**Issue by federicohml** [NVIDIA/TRTorch#338]
## ❓ Question

My network has a single input of the following shape [1, 3, 224, 224]. I a trying to create the trtorch::CompileSpec as follows
`auto compile_settings = trtorch::CompileSpec({1, 3, 224, 224});` however I am getting the following output

````
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/conversion/conversion.cpp:135] Expected input_tensors.size() == input_dims.size() to be true but got false
Expected dimension specifications for all input tensors, but found 1 input tensors and 4 dimension specs (conversion.AddInputs)
````
I am wondering whether the constructor is a vector of input shapes? If so, doing 

````
std::vector<std::vector<int64_t>> input_dims = {{1, 3, 224, 224}};
auto compile_settings = trtorch::CompileSpec(input_dims);
````
gives the following error

````
ERROR: [TRTorch] - Requested converter for aten::adaptive_max_pool2d, but no such converter was found
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/conversion/conversion.cpp:108] Expected converter to be true but got false
Unable to convert node: %512 : Tensor, %513 : Tensor = aten::adaptive_max_pool2d(%511, %7) # /home/federico/.local/lib/python3.8/site-packages/torch/nn/functional.py:844:0 (conversion.AddLayer)
Schema: aten::adaptive_max_pool2d(Tensor self, int[2] output_size) -> (Tensor, Tensor)
Converter for aten::adaptive_max_pool2d requested, but no such converter was found.
If you need a converter for this operator, you can try implementing one yourself
or request a converter: https://www.github.com/NVIDIA/TRTorch/issues
````

So my question is, which approach is the correct one. If the second is, I can try to implement the converter myself but I want to be sure what has to be passed to create a correct `CompileSpec`.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.7.1
 - CPU Architecture: amd64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): `LD_LIBRARY_PATH=$(pwd)/bazel-TRTorch/external/libtorch/lib/:$(pwd)/bazel-TRTorch/external/cudnn/lib64/:$(pwd)/bazel-TRTorch/external/tensorrt/lib/:/usr/local/cuda/lib64/:$LD_LIBRARY_PATH bazel run //adv_test:adv_trtorch -c opt --jobs=3 --distdir third_party/dist_dir/x86_64-linux-gnu/`
 - Are you using local sources or building from archives: archives
 - Python version: 3.8
 - CUDA version: 11.0
 - GPU models and configuration: GTX 1050
 - Any other relevant information:

**Comment by federicohml** [comment]
Code being used is the one in the issue #337 with the minor twist of adding the following after loading the TorchScript model

````
  std::cout << "Compiling TorchScript Model to TRTorch";
  std::vector<std::vector<int64_t>> input_dims = {{1, 3, 224, 224}};
  auto compile_settings = trtorch::CompileSpec(input_dims);
  // auto compile_settings = trtorch::CompileSpec({1, 3, 224, 224});
  auto trt_module = trtorch::CompileGraph(ts_module, compile_settings);
  std::cout << " ... OK" << std::endl;
````

**Comment by peri044** [comment]
The input should be a vector of vectors. The second approach is correct Eg: [https://github.com/NVIDIA/TRTorch/blob/master/cpp/trtorchexec/main.cpp#L58](url)
Also, adaptive_max_pool is in works. You can check this PR : [https://github.com/NVIDIA/TRTorch/pull/328](url) to see if it resolves your converter issue.

**Comment by federicohml** [comment]
Thank you, will look forward to that PR. In the meantime will try to avoid AdaptiveMaxPool2D for inference.
