### ISSUE TITLE
✨[Feature] Implement Relu6 activation converter

### ISSUE THREAD

**Issue by peri044** [NVIDIA/TRTorch#339]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We would like to support Relu6 activation
**Describe alternatives you've considered**
Express it as min( max(0, x), 6)

**Additional context**
[https://pytorch.org/docs/stable/generated/torch.nn.ReLU6.html](url)
We should implement this converter as a standalone example (More info:  [https://github.com/NVIDIA/TRTorch/issues/330](url))

**Comment by narendasan** [comment]
Already supported via hardtanh
