### ISSUE TITLE
🐛 [Bug] Encountered bug when using TRTorch

### ISSUE THREAD

**Issue by algoscale1** [NVIDIA/TRTorch#364]
##  Bug Description
When I tried to compile the ultralytics/yolov5 model. I got this error: 

RuntimeError: [enforce fail at core/conversion/conversion.cpp:183] Expected it != ctx->value_tensor_map.end() && it->second to be true but got false
No corresponding output TRT Tensor found for TorchScript output: 951

## To Reproduce

model = torch.load("upsample.pt")
model = model['model'].to(device_gpu)
model.eval()

traced = torch.jit.trace(model, torch.rand((1,3,512,512)).to(device_gpu))
traced = traced.to(device_gpu)

compiled_model = trtorch.compile(traced , {
    "input_shapes": [(1,3,512,512)],
     "op_precision": torch.half,
     "max_batch_size":1
 })

## Expected behavior
1.  Model gets converted to TensorRT.
(When I tried to convert Resnet18 model to TensorRT. It got converted without any error.)

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version 1.6.0
 - CPU Architecture:
 - Ubuntu 18.0
 - How you installed PyTorch : pip
 - Python version: 3.7
 - CUDA version: 10.2 
 - GPU models and configuration: RTX series NVIDIA GPU, 16GB RAM, i5-7500 CPU

## Additional context
1. Getting converter issue for aten::slice and aten::upsample_nearest2d (skipped that layers from architecture).

**Comment by peri044** [comment]
My TRTorch is built with pytorch 1.7.1 + cuda-11. I followed this [https://github.com/ultralytics/yolov5/issues/251](url) to export the model to Torchscript. However, I see a different error 
```
Found the value to be: [<__torch__.torch.classes._trtorch_eval_ivalue_types.TensorContainer object at 0x55873376f5f0>, <__torch__.torch.classes._trtorch_eval_ivalue_types.TensorContainer object at 0x558734c7aac0>, <__torch__.torch.classes._trtorch_eval_ivalue_types.TensorContainer object at 0x558734c7c3f0>]
terminate called after throwing an instance of 'trtorch::Error'
  what():  [enforce fail at core/conversion/conversion.cpp:193] Unknown output type. Only a single tensor or a TensorList type is supported.
```
Can you confirm if you used the same export process to generate the torchscript model ? Can you try with the latest configuration on master (using pytorch 1.7.1 + cuda-11) ?. If you see a different error, can you provide your torchscript model for us  to debug ?

**Comment by algoscale1** [comment]
Actually we are using this configuration for Deepstream also so I cant upgrade the configuration to cuda-11.
I have used this [repo](https://drive.google.com/file/d/1UuFJQEtpka5s8qpmA1noVMD2KimOhR1o/view?usp=sharing) for inference.
I have modified the layers( due to aten::slice and aten::upsample_nearest2d error with latest release).
I Model I'm using is this one [model](https://drive.google.com/file/d/19A_GRbzatoUporV2BxQlgQNjZS1w3Qpw/view?usp=sharing). It's based on this architecture..

# parameters
nc: 101  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# YOLOv5 backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   [-1, 1, Conv, [256, 3, 2]],  # 3-P3/8
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3, [1024, False]],  # 9
  ]

# YOLOv5 head
head:
  [[-1, 1, Conv, [512, 1, 1]],
   [-1, 1, Upconv, [512, 512]],
   [[-1, 6], 1, Concat, [1]],  # cat backbone P4
   [-1, 3, C3, [512, False]],  # 13

   [-1, 1, Conv, [256, 1, 1]],

   [-1, 1, Upconv, [256, 256]],
   [[-1, 4], 1, Concat, [1]],  # cat backbone P3
   [-1, 3, C3, [256, False]],  # 17 (P3/8-small)

   [-1, 1, Conv, [256, 3, 2]],
   [[-1, 14], 1, Concat, [1]],  # cat head P4
   [-1, 3, C3, [512, False]],  # 20 (P4/16-medium)

   [-1, 1, Conv, [512, 3, 2]],
   [[-1, 10], 1, Concat, [1]],  # cat head P5
   [-1, 3, C3, [1024, False]],  # 23 (P5/32-large)

   [[17, 20, 23], 1, Detect, [nc, anchors]],  # Detect(P3, P4, P5)
  ]
  
  **Here's the output logs I'm getting after running the code mentioned in Bug.**
  TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.
  module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, strict, _force_outplace)
Traceback (most recent call last):
  File "test.py", line 65, in <module>
    "max_batch_size":1
  File "/usr/local/lib/python3.7/dist-packages/trtorch/_compiler.py", line 61, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: [enforce fail at core/conversion/conversion.cpp:183] Expected it != ctx->value_tensor_map.end() && it->second to be true but got false
No corresponding output TRT Tensor found for TorchScript output: 951

**Comment by algoscale1** [comment]
**When I tried to get rid of the Tracer warning for output(by changing the list of Tensor to just Tensor). I got this error...**
ERROR: [TRTorch Conversion Context] - Try increasing the workspace size with IBuilderConfig::setMaxWorkspaceSize() if using IBuilder::buildEngineWithConfig, or IBuilder::setMaxWorkspaceSize() if using IBuilder::buildCudaEngine.
ERROR: [TRTorch Conversion Context] - ../builder/tacticOptimizer.cpp (1814) - TRTInternal Error in computeCosts: 0 (Could not find any implementation for node %602 : Float(1:524288, 512:1024, 32:32, 32:1) = aten::_convolution(%601, %self.model.11.conv_1.weight, %self.model.11.conv_1.bias, %7, %8, %9, %13, %8, %15, %14, %14, %13), scope: __module.model.11/__module.model.11.conv_1 # /usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py:907:0.)
ERROR: [TRTorch Conversion Context] - ../builder/tacticOptimizer.cpp (1814) - TRTInternal Error in computeCosts: 0 (Could not find any implementation for node %602 : Float(1:524288, 512:1024, 32:32, 32:1) = aten::_convolution(%601, %self.model.11.conv_1.weight, %self.model.11.conv_1.bias, %7, %8, %9, %13, %8, %15, %14, %14, %13), scope: __module.model.11/__module.model.11.conv_1 # /usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py:907:0.)
Segmentation fault
