### ISSUE TITLE
🐛 [Bug] Memory leak in ConversionCtx::SerializeEngine()

### ISSUE THREAD

**Issue by SakodaShintaro** [NVIDIA/TRTorch#375]
##  Bug Description
Using `trtorch::CompileGraph` many times will increase memory usage.

## To Reproduce
[Source code](https://github.com/SakodaShintaro/trtorch-test/blob/7e9f7a457b3570b40e5aa938ac400aaf5e0028ba/main.cpp)

```cpp
#include <torch/script.h>
#include <trtorch/trtorch.h>
using namespace std;

void compile() {
  constexpr int64_t INPUT_CHANNEL_NUM = 256;
  constexpr int64_t WIDTH = 32;
  torch::jit::Module module = torch::jit::load("model.ts");
  module.to(torch::kCUDA);
  module.eval();

  std::vector<int64_t> in_sizes = {1, INPUT_CHANNEL_NUM, WIDTH, WIDTH};
  trtorch::CompileSpec::InputRange range(in_sizes);
  trtorch::CompileSpec info({range});
  module = trtorch::CompileGraph(module, info);
}

int main() {
  for (int64_t i = 0; i < 10000; i++) {
    cout << i << endl;
    compile();
  }
}
```

[Dockerfile](https://github.com/SakodaShintaro/trtorch-test/blob/7e9f7a457b3570b40e5aa938ac400aaf5e0028ba/docker/Dockerfile)

## What seems to be the cause
When I verified it with Valgrind, it seemed that the cause was ConversionCtx::SerializeEngine. Looking at the code, it seemed that the `serialized_engine` isn't released. After making the following modifications, the memory leak no longer occurs.

```
diff --git a/core/conversion/conversionctx/ConversionCtx.cpp b/core/conversion/conversionctx/ConversionCtx.cpp
index ff23692..c241f9c 100644
--- a/core/conversion/conversionctx/ConversionCtx.cpp
+++ b/core/conversion/conversionctx/ConversionCtx.cpp
@@ -147,7 +147,9 @@ std::string ConversionCtx::SerializeEngine() {
   auto engine = builder->buildEngineWithConfig(*net, *cfg);
   auto serialized_engine = engine->serialize();
   engine->destroy();
-  return std::string((const char*)serialized_engine->data(), serialized_engine->size());
+  std::string result = std::string((const char*)serialized_engine->data(), serialized_engine->size());
+  serialized_engine->destroy();
+  return result;
 }
 ```

I would appreciate it if you could respond appropriately.

**Comment by narendasan** [comment]
Good catch! Thanks for reporting this! We totally except PRs so in the future if you have a patch for a bug you find, feel free to open one up in addition to the bug.

**Comment by SakodaShintaro** [comment]
Thank you for your prompt response. I'm not used to team development, but I might try it next time.
