### ISSUE TITLE
🐛 [Bug] Installing TRTorch from source ends up in segmentation fault

### ISSUE THREAD

**Issue by Belval** [NVIDIA/TRTorch#377]
##  Bug Description

After compiling TRTorch from source I get a Segmentation Fault when running `python3 setup.py install`.

## To Reproduce

1. Download TensorRT 7.2 (TensorRT-7.2.2.3.Ubuntu-18.04.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz)
2. Download CuDNN 8.1 (cudnn-11.2-linux-x64-v8.1.0.77.tgz)
3. Put both in `third_party/dist_dir/x86_64-linux-gnu`
4. `bazelisk-linux-amd64 build //:libtrtorch --compilation_mode opt --distdir third_party/dist_dir/x86_64-linux-gnu/`
5. `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/bazel-TRTorch/external/libtorch/lib`
6. `cd py && python3 setup.py install`

I get a segmentation fault, when using `faulthandler` to obtain a stacktrace I get the following:

```py
Fatal Python error: Segmentation fault

Current thread 0x00007f5f48d7b740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1043 in create_module
  File "<frozen importlib._bootstrap>", line 583 in module_from_spec
  File "<frozen importlib._bootstrap>", line 670 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 190 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 953 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "setup.py", line 15 in <module>
Segmentation fault (core dumped)
```

Line 15 is the torch import `from torch.utils import cpp_extension`, I installed pytorch 1.7.1 with `pip3 install torch==1.7.1`.

## Expected behavior

TRTorch is installed, no segmentation fault is raised.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.7.1
 - CPU Architecture: AMD64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): N/A
 - Are you using local sources or building from archives: N/A
 - Python version: 3.7.6
 - CUDA version: 11.0
 - GPU models and configuration: Tesla V100-SXM2
 - Any other relevant information: N/A

## Additional context

I only want to have TRTorch for Pytorch 1.7.1 which is not available in the release tab. If there is another way to download it that would work for me.

**Comment by narendasan** [comment]
When building the python package all you need to do is run `python3 setup.py install`. You do not need to first build the C++ library. My guess is the segfault is coming from including `libtorch` in your `LD_LIBRARY_PATH`. PyTorch distributes libtorch with CXX11 ABI and pre-cxx11-abi but PyTorch uses solely pre-cxx11-abi. Having libtorch-cxx11 in the path will cause issues with importing pytorch.

Try unsetting your LD_LIBRARY_PATH, then insuring CUDA, TensorRT, and cuDNN are in in your LD_LIBRARY_PATH but not libtorch. 

Then try

``` 
bazel clean 
python3 setup.py install
```

**Comment by Belval** [comment]
I tried without libtorch in my path but I still can't get a valid install (`python3 setup.py install` completed without errors):

```py
Python 3.7.6 (default, Jan  8 2020, 19:59:22)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trtorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hiero_efs/HieroUsers/belvae/Workspace2/src/RekognitionHieroPyTorchTimer/RekognitionHieroPytorchTimer/TRTorch/py/trtorch/__init__.py", line 11, in <module>
    from trtorch._compiler import *
  File "/hiero_efs/HieroUsers/belvae/Workspace2/src/RekognitionHieroPyTorchTimer/RekognitionHieroPytorchTimer/TRTorch/py/trtorch/_compiler.py", line 5, in <module>
    import trtorch._C
ModuleNotFoundError: No module named 'trtorch._C'
>>> exit()
```

Here is what my `$LD_LIBRARY_PATH` looked like:

```
/home/ubuntu/TRTorch/third_party/dist_dir/x86_64-linux-gnu/TensorRT-7.2.2.3/lib/ /home/ubuntu/TRTorch/third_party/dist_dir/x86_64-linux-gnu/cuda/lib64/
/usr/lib64/openmpi/lib/
/usr/local/cuda/lib64/
/usr/local/lib:/usr/lib/
/usr/local/cuda/extras/CUPTI/lib64/
/usr/local/mpi/lib
/lib/
/usr/local/cuda/lib64
/usr/local/lib
/usr/lib
/usr/local/cuda/extras/CUPTI/lib64
/usr/local/cuda/lib
/usr/local/mpi/lib
/usr/lib64/openmpi/lib/
/usr/local/cuda/lib64
/usr/local/lib
/usr/lib
/usr/local/cuda/extras/CUPTI/lib64
/usr/local/mpi/lib
/lib/
```

**Comment by Belval** [comment]
Regarding my last comment, I reopened a new shell and I was able to import TRTorch just fine.

Thank you for your time, I really like your project.

**Comment by suyashhchougule** [comment]
> When building the python package all you need to do is run `python3 setup.py install`. You do not need to first build the C++ library. My guess is the segfault is coming from including `libtorch` in your `LD_LIBRARY_PATH`. PyTorch distributes libtorch with CXX11 ABI and pre-cxx11-abi but PyTorch uses solely pre-cxx11-abi. Having libtorch-cxx11 in the path will cause issues with importing pytorch.
> 
> Try unsetting your LD_LIBRARY_PATH, then insuring CUDA, TensorRT, and cuDNN are in in your LD_LIBRARY_PATH but not libtorch.
> 
> Then try
> 
> ```
> bazel clean 
> python3 setup.py install
> ```

I did instructed but still getting segmentation fault (core dumped)
I am compiling on jetson nano with Jetpack 4.6, CUDA 10.2 , TensorRT 8, Torch 1.9.0

Please reply. what went wrong ?

**Comment by suyashhchougule** [comment]
> > When building the python package all you need to do is run `python3 setup.py install`. You do not need to first build the C++ library. My guess is the segfault is coming from including `libtorch` in your `LD_LIBRARY_PATH`. PyTorch distributes libtorch with CXX11 ABI and pre-cxx11-abi but PyTorch uses solely pre-cxx11-abi. Having libtorch-cxx11 in the path will cause issues with importing pytorch.
> > Try unsetting your LD_LIBRARY_PATH, then insuring CUDA, TensorRT, and cuDNN are in in your LD_LIBRARY_PATH but not libtorch.
> > Then try
> > ```
> > bazel clean 
> > python3 setup.py install
> > ```
> 
> I did instructed but still getting segmentation fault (core dumped) while importing in python3
> I am compiling on jetson nano with Jetpack 4.6, CUDA 10.2 , TensorRT 8, Torch 1.9.0
> 
> Please reply. what went wrong ?

Turns out,  Had to use --use-cxx11-abi

**Comment by suyashhchougule** [comment]
> > > When building the python package all you need to do is run `python3 setup.py install`. You do not need to first build the C++ library. My guess is the segfault is coming from including `libtorch` in your `LD_LIBRARY_PATH`. PyTorch distributes libtorch with CXX11 ABI and pre-cxx11-abi but PyTorch uses solely pre-cxx11-abi. Having libtorch-cxx11 in the path will cause issues with importing pytorch.
> > > Try unsetting your LD_LIBRARY_PATH, then insuring CUDA, TensorRT, and cuDNN are in in your LD_LIBRARY_PATH but not libtorch.
> > > Then try
> > > ```
> > > bazel clean 
> > > python3 setup.py install
> > > ```
> > 
> > 
> > I did instructed but still getting segmentation fault (core dumped) while importing in python3
> > I am compiling on jetson nano with Jetpack 4.6, CUDA 10.2 , TensorRT 8, Torch 1.9.0
> > Please reply. what went wrong ?
> 
> Turns out, Had to use  `--use-cxx11-abi`

**Comment by narendasan** [comment]
Yeah on jetson because NVIDIA's build of PyTorch uses the CXX11 ABI you need this additional flag for python. https://nvidia.github.io/TRTorch/tutorials/installation.html#building-natively-on-aarch64-jetson
