### ISSUE TITLE
❓ [Question] PyTorch 1.8 Support

### ISSUE THREAD

**Issue by developer0hye** [NVIDIA/TRTorch#391]
## What you have already tried
PyTorch 1.8(stable) is released recently.

When will TRTorch be compatible to PyTorch 1.8?

**Comment by narendasan** [comment]
There is a PR for this already if you need support today (https://github.com/NVIDIA/TRTorch/pull/389). It is currently missing some changes for the backend api but other than that works with 1.8. A release will be cut as soon as the Jetson build of 1.8 is released
