### ISSUE TITLE
Create some sort of serialization / deserialization functionality

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#40]
With INT8 about to land, would be a pain to have to calibrate from scratch every time. There should be some mechanism to save and load modules with the TRT engine included.

**Comment by salexspb** [comment]
That would be awesome to have proper serialization! I would also add that for large scale deployments this is a must have even for faster converting fp16. As if you have a lot of models, converting all of them on restart would be quite expensive.
