### ISSUE TITLE
how to compile on windows？

### ISSUE THREAD

**Issue by statham123** [NVIDIA/TRTorch#411]

**Comment by narendasan** [comment]
There was unofficial/community support for Windows that worked early on in the project but it has been neglected. You should in theory be able to use similar bazel build commands after editing the WORKSPACE file to point to dependencies and remove the python dependencies. We don't currently have the resources to maintain Windows but we are happy to provide advice where we can (I don't have a ton of experience building on Windows) if someone wants to take this on.
