### ISSUE TITLE
🐛 [Bug] Segfault when converting AvgPool2d

### ISSUE THREAD

**Issue by efengler** [NVIDIA/TRTorch#417]
##  Bug Description

I' trying to convert a model containing AvgPool2d layer with kernel_size=2, stride=2 and ceil_mode=True. When layer input size is divisible by 2 (so it would work the same as with ceil_mode=False), I'm getting the following error:

`ERROR: [TRTorch Conversion Context] - ../builder/cudaTiledPoolingBuilder.cpp (120) - Assertion Error in addTiledPath: 0 ((validation::is32(*src.region) || validation::is16C2(*src.region) || validation::is8C4(*src.region)) && (possibleTiledPath(src.region->getDataType(), src.region->getLgScalarsPerVector(), params)))
Segmentation fault`
 
It doesn't seem to happen for different strides and it works fine when the input size isn't divisible by 2. Also, replacing the layer with MaxPool2d or two AvgPool2d layers, the first one with kernel_size and stride (2,1) and the other one with (1,2) results in successful conversion.

## To Reproduce

Run the following code:

```import torch
import torch.nn as nn
import trtorch


class MyModule(nn.Module):
	def __init__(self):
		super(MyModule, self).__init__()
		self.avg_pool = torch.nn.AvgPool2d(kernel_size=2, stride=2, ceil_mode=True)

	def forward(self, x):
		return self.avg_pool(x)

shape = (1,4,4,4)

model = MyModule()
script_model = torch.jit.script(model.cuda().eval())

compile_settings = {
        "input_shapes": [shape],
}

compiled_model = trtorch.compile(script_model, compile_settings)

x = torch.randn(shape)
output = compiled_model(x.cuda())
print(output)
```

## Expected behavior

The code should convert the model and print the output tensor.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version: 1.7.0 
 - CPU Architecture: aarch64 (Jetson Xavier NX)
 - OS (e.g., Linux): Ubuntu 18.04.5
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): dedicated wheel for Jetson
 - Build command you used (if compiling from source): -
 - Are you using local sources or building from archives: -
 - Python version: 3.6.9
 - CUDA version: 10.2
 - GPU models and configuration: -
 - Any other relevant information: -

**Comment by narendasan** [comment]
I was able to replicate this issue on x86 as well. Seems like its coming from TensorRT. We will investigate further and see if its a known issue with them.

**Comment by peri044** [comment]
There is some discrepancy between `ceil_mode` and `poolingLayer->setAverageCountExcludesPadding(exclude_padding)` behavior. Filed and being tracked in [this issue](https://github.com/onnx/onnx-tensorrt/issues/663).

**Comment by peri044** [comment]
@efengler  Thanks for reporting. This bug is fixed in next release of TensorRT. So, TRTorch can handle it then.

**Comment by narendasan** [comment]
Reopening until fix can be verified in TRT-Next

**Comment by narendasan** [comment]
@peri044 can we check this on the TRT8 branch?

**Comment by peri044** [comment]
Tested with latest TRTorch 0.4 with TRT8. This issue is fixed.
