### ISSUE TITLE
❓ [Question] How can I pull TRTorch docker image?

### ISSUE THREAD

**Issue by Tshzzz** [NVIDIA/TRTorch#420]
## ❓ Question
I use the command to pull TRTorch docker image
```
sudo docker pull docker.pkg.github.com/nvidia/trtorch/docgen:0.3.0
```
Get respose  unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.

I can't find anyway to accsee the token.

**Comment by narendasan** [comment]
Are you logged in to the GitHub registry on your machine with docker login? Also the docgen container is just an environment to build our docs in CI, not sure how useful you'd find it. We tried uploading a release container but it was too large for GitHub. Likely in the future there will be some TRTorch container on NGC you can access but it's a lower priority for us.

**Comment by Tshzzz** [comment]
> Are you logged in to the GitHub registry on your machine with docker login? Also the docgen container is just an environment to build our docs in CI, not sure how useful you'd find it. We tried uploading a release container but it was too large for GitHub. Likely in the future there will be some TRTorch container on NGC you can access but it's a lower priority for us.

**Comment by Tshzzz** [comment]
> Are you logged in to the GitHub registry on your machine with docker login? Also the docgen container is just an environment to build our docs in CI, not sure how useful you'd find it. We tried uploading a release container but it was too large for GitHub. Likely in the future there will be some TRTorch container on NGC you can access but it's a lower priority for us.

thank you for your reply.
