### ISSUE TITLE
 trtorch._C.compile_graph - RuntimeError: required keyword attribute 'use_input_stats' is undefined

### ISSUE THREAD

**Issue by saulzar** [NVIDIA/TRTorch#426]
##  Bug Description

  File "/home/oliver/miniconda3/lib/python3.7/site-packages/trtorch/_compiler.py", line 66, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: required keyword attribute 'use_input_stats' is undefined

## To Reproduce

  ```
import trtorch
  import torch
  import torch.nn as nn

  m = torch.nn.Conv2d(3, 10, (3, 3))
  inp = torch.zeros(1, 3, 64, 64)

  traced = torch.jit.trace(m, inp)

  compile_settings = dict(
    input_shapes = [inp.shape],
    op_precision = torch.half
  )

  trtorch.compile(traced, compile_settings)

```
```

  trtorch.compile(traced, compile_settings)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/trtorch/_compiler.py", line 66, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: required keyword attribute 'use_input_stats' is undefined

```

## Expected behavior

Expect to run without exception.

## Environment

 - TRTorch Version: github 0.3.0a0
 - PyTorch Version: 1.8.1
 - CPU Architecture: amd64
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Build command you used (if compiling from source):  bazel build //:libtrtorch --compilation_mode opt --distdir third_party/dist_dir/x86_64-linux-gnu; python setup.py install

 - Are you using local sources or building from archives: From sources - Python version:
 - CUDA version: 11.1
 - GPU models and configuration: RTX 2070
 - Any other relevant information:

**Comment by peri044** [comment]
This error seems to be specific to pytorch 1.8.1 issue. We currently support torch 1.8.0 + cuda-11.1. Can you try with this configuration ? You can install them by 
```
pip install torch==1.8.0+cu111 torchvision==0.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
```
Using the above config, your test script runs fine for me.
