### ISSUE TITLE
❓ [Question] Does TRTorch support autograd in inference?

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [NVIDIA/TRTorch#429]
## ❓ Question

Some models can contain autograd as part of their inference pass; a simple example, which does compile to TorchScript, would be:
```python
import torch
class M(torch.nn.Module):
    def forward(self, x):
        x.requires_grad_(True)
        y = x**2
        return torch.autograd.grad([y.sum()], [x])[0]

m = M()
m(3*torch.ones(3))  # =>  tensor([6., 6., 6.])
ms = torch.jit.script(m)
ms(3*torch.ones(3))  # => tensor([6., 6., 6.])
```

I know `autograd.grad` isn't in the list of supported operations, but I'm curious whether something like this would be possible in TRTorch, or if it is fundamentally incompatible with the TensorRT design.

Thanks!

**Comment by narendasan** [comment]
I dont think that TensorRT has any facilities for Autograd so I am not sure how we would support this. I don't think we could support this via plugin or something either without something really involved.

**Comment by Linux-cpp-lisp** [comment]
Hi @narendasan : that makes sense, thank you for confirming.
