### ISSUE TITLE
Build Project failed with Bazel

### ISSUE THREAD

**Issue by alanzhai219** [NVIDIA/TRTorch#45]
Hi,

I configure the env and try to build such project. 
INFO: Analyzed target //:libtrtorch (34 packages loaded, 1830 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base /home/xxx/.cache/bazel/_bazel_xxx/2ed6247d0d5238dab6f58f41a8e8ad4b/sandbox
ERROR: missing input file 'external/tensorrt/lib/x86_64-linux-gnu/libnvinfer.so', owner: '@tensorrt//:lib/x86_64-linux-gnu/libnvinfer.so'
ERROR: /home/xxx/2ed6247d0d5238dab6f58f41a8e8ad4b/external/tensorrt/BUILD.bazel:15:1: @tensorrt//:nvinfer_lib: missing input file '@tensorrt//:lib/x86_64-linux-gnu/libnvinfer.so'
Target //:libtrtorch failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/xxx/.cache/bazel/_bazel_xxxd5238dab6f58f41a8e8ad4b/external/tensorrt/BUILD.bazel:15:1 1 input file(s) do not exist
INFO: Elapsed time: 2.964s, Critical Path: 0.13s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

could you help solve such errors or provide more env setting details?
I have email @narendasan and please check it.
Thanks.

**Comment by narendasan** [comment]
What is the location of the TensorRT installation on your machine?

**Comment by narendasan** [comment]
You may need to edit both the `WORKSPACE` file and the `third_party/tensorrt/BUILD` file to point to the location of your TensorRT installation. I can give suggestions but need a bit more information about where stuff is located on your machine.

**Comment by alanzhai219** [comment]
Could you check your mailbox naren@narendasan.com?
/home/xxx/
--- cuda-10.1(cudnn  has been copied in such dir)
--- tensorrt(which is TensorRT dir)
--- workspace/TRTorch

**Comment by narendasan** [comment]
The way bazel assembles paths is by concatenating the root path specified in the `WORKSPACE` file (expected to be `/usr/` since that is the installation root for the debian package) and the path from the root to the actual file specified in the BUILD file (for TRT headers this is expected to be `include/XXX.h` and for libraries it is expected to be `/lib/x86_64-linux-gnu/XXX.so`). So you would look for headers in `/usr/include/XXX.h` and libraries in /usr/lib/x86_64-linux-gnu/XXX.so`.

You will probably need to change the tensorrt section of the `WORKSPACE` file to something like this:
```py
new_local_repository(
   name = "tensorrt",
   path = "/home/xxx/tensorrt/",
   build_file = "@//third_party/tensorrt/BUILD"
)
```
and `third_party/tensorrt/BUILD` to something like this 
```py
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nvinfer_headers",
    hdrs = glob([
        "include/NvInfer*.h",
    ], exclude=[
        "include/NvInferPlugin.h",
        "include/NvInferPluginUtils.h"
    ]),
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_import(
    name = "nvinfer_lib",
    shared_library = "lib/libnvinfer.so",
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvinfer",
    deps = [
        "nvinfer_headers",
        "nvinfer_lib",
        "@cuda//:cudart",
        "@cuda//:cublas",
        "@cudnn//:cudnn"
    ],
    visibility = ["//visibility:public"],
)

####################################################################################

cc_import(
    name = "nvparsers_lib",
    shared_library = "lib/libnvparsers.so",
    visibility = ["//visibility:private"],
)


cc_library(
    name = "nvparsers_headers",
    hdrs = [
        "include/NvCaffeParser.h",
        "include/NvOnnxParser.h",
        "include/NvOnnxParserRuntime.h",
        "include/NvOnnxConfig.h",
        "include/NvUffParser.h"
    ],
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvparsers",
    deps = [
        "nvparsers_headers",
        "nvparsers_lib",
        "nvinfer"
    ],
    visibility = ["//visibility:public"],
)

####################################################################################

cc_import(
    name = "nvonnxparser_lib",
    shared_library = "lib/libnvonnxparser.so",
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvonnxparser_headers",
    hdrs = [
        "include/NvOnnxParser.h",
        "include/NvOnnxParserRuntime.h",
        "include/NvOnnxConfig.h"
    ],
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvonnxparser",
    deps = [
        "nvonnxparser_headers",
        "nvonnxparser_lib",
        "nvinfer"
    ],
    visibility = ["//visibility:public"],
)

####################################################################################

cc_import(
    name = "nvonnxparser_runtime_lib",
    shared_library = "lib/libnvonnxparser_runtime.so",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "nvonnxparser_runtime_header",
    hdrs = ["include/NvOnnxParserRuntime.h"],
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvonnxparser_runtime",
    deps = [
        "nvparsers_headers",
        "nvparsers_lib",
        "nvinfer"
    ],
    visibility = ["//visibility:public"],
)
####################################################################################

cc_import(
    name = "nvcaffeparser_lib",
    shared_library = "lib/libnvcaffe_parsers.so",
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvcaffeparser_headers",
    hdrs = ["include/NvCaffeParser.h"],
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvcaffeparser",
    deps = [
        "nvcaffeparser_headers",
        "nvcaffeparser_lib",
        "nvinfer"
    ],
    visibility = ["//visibility:public"],
)

####################################################################################

cc_import(
    name = "nvinferplugin_lib",
    shared_library = "lib/libnvinfer_plugin.so",
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvinferplugin_headers",
    hdrs = glob(["include/NvInferPlugin*.h"]),
    includes = ["include/"],
    visibility = ["//visibility:private"],
)

cc_library(
    name = "nvinferplugin",
    deps = [
        "nvinferplugin_headers",
        "nvinferplugin_lib",
        "nvinfer"
    ],
    visibility = ["//visibility:public"],
)
```

**Comment by alanzhai219** [comment]
Thanks for your quick reply. 
Following your guide, I can compile the project. But it reports unordered_map errors and it seems gcc-5 is a bit old. I will try a higher gcc.
After I build it successfully, I will close it.
Thanks,
Alan
