### ISSUE TITLE
✨[Feature] could you fallback to the original graph when compile failed other than crash  directly

### ISSUE THREAD

**Issue by kiddyjinjin** [NVIDIA/TRTorch#470]
**Is your feature request related to a problem? Please describe.**

In my situation,  I want to  TRY TO use trtorch to compile my torchscript,  if failed,  I need to do something else. 
so,  could you fallback to the original graph when compile failed other than crash  directly?

**Describe the solution you'd like**

how about  change the API below
`torch::jit::script::Module CompileGraph(const torch::jit::script::Module& mod, CompileSpec cfg) `
to
`int CompileGraph(const torch::jit::script::Module& mod,  torch::jit::script::Module& new_mod,  CompileSpec cfg) `

**Describe alternatives you've considered**

**Comment by narendasan** [comment]
I don't think we are going to implement this API change, it would be a breaking change and doesnt feel like it adds many ergonomic benefits. We do throw exceptions that you can catch and handle. TRTorch does not modify the source module and so it should be perfectly safe to use the original model in the case that compilation failed. If you are seeing crashes like segfaults, please file those as bugs separately.

**Comment by narendasan** [comment]
Also out of interest on how people are using TRTorch, do you include TRTorch inline in your deployed application or is this part of a model freezing pipeline that creates an artifact to be shipped with your production application? It's an interesting use case to try TRTorch compilation but then if it fails do something else, I am wondering what the something else is.

**Comment by kiddyjinjin** [comment]
> Also out of interest on how people are using TRTorch, do you include TRTorch inline in your deployed application or is this part of a model freezing pipeline that creates an artifact to be shipped with your production application? It's an interesting use case to try TRTorch compilation but then if it fails do something else, I am wondering what the something else is.

well. Long before your latest release，there is no partition support in TRTorch. And I can’t trans my complex model
to TRTorch cause  some of the converters  are not supported,  so I try to  extract  the fully supported subgraphs to TRTorch,  but still, i meet some failure(like I mentioned in [)and](https://github.com/NVIDIA/TRTorch/issues/469) that's when I added this issue.

back to this issue.  I have  added  `try/catch` to capture the failure and then fallback to the original subgraphs myself.
