### ISSUE TITLE
✨[Feature] Add support for TRT engine embedding with trtorchc

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#472]
**Is your feature request related to a problem? Please describe.**

Let users who already have a TRT engine use trtorchc to embed that engine in a TorchScript module.

**Describe the solution you'd like**

A new embedding option for trtorchc

**Describe alternatives you've considered**

**Additional context**

**Comment by ncomly-nvidia** [comment]
Comment added by Nick Comly in Aha! - [View](https://nvaiinfra.aha.io/comments/6987518372268488468)

Naren: "one days work" [https://nvidia.slack.com/archives/C01414STH0T/p1626906681119300?thread\_ts=1626906653.119100&cid=C01414STH0T](https://nvidia.slack.com/archives/C01414STH0T/p1626906681119300?thread_ts=1626906653.119100&cid=C01414STH0T)
