### ISSUE TITLE
❓ Is it possible to use TRTorch with batchedNMSPlugin for TensorRT?

### ISSUE THREAD

**Issue by VRSEN** [NVIDIA/TRTorch#473]
## What you have already tried

Hi, I am trying to convert detectron2 traced keypoint-rcnn model that contains ops from torchvision like torchvision::nms. I get the following error:

> 
> terminate called after throwing an instance of 'torch::jit::ErrorReport'
>  what():  
> Unknown builtin op: torchvision::nms.
> Could not find any similar ops to torchvision::nms. This op may not exist or may not be currently supported in TorchScript.
> :
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/ops/boxes.py", line 36
>     """
>     _assert_has_ops()
>     return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
>            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 26
>   _8 = __torch__.torchvision.extension._assert_has_ops
>   _9 = _8()
>   _10 = ops.torchvision.nms(boxes, scores, iou_threshold)
>         ~~~~~~~~~~~~~~~~~~~ <--- HERE
>   return _10
> 'nms' is being compiled since it was called from 'batched_nms'
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/ops/boxes.py", line 75
>         offsets = idxs.to(boxes) * (max_coordinate + torch.tensor(1).to(boxes))
>         boxes_for_nms = boxes + offsets[:, None]
>         keep = nms(boxes_for_nms, scores, iou_threshold)
>                ~~~ <--- HERE
>         return keep
> Serialized   File "code/__torch__/torchvision/ops/boxes.py", line 18
>     _7 = torch.slice(offsets, 0, 0, 9223372036854775807, 1)
>     boxes_for_nms = torch.add(boxes, torch.unsqueeze(_7, 1), alpha=1)
>     keep = __torch__.torchvision.ops.boxes.nms(boxes_for_nms, scores, iou_threshold, )
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>     _0 = keep
>   return _0
> 'batched_nms' is being compiled since it was called from 'RPN.forward'
> Serialized   File "code/__torch__/detectron2/modeling/proposal_generator/rpn.py", line 19
>     argument_9: Tensor,
>     image_size: Tensor) -> Tensor:
>     _0 = __torch__.torchvision.ops.boxes.batched_nms
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
>     _1 = self.rpn_head
>     _2 = (self.anchor_generator).forward(argument_1, argument_2, argument_3, argument_4, argument_5, argument_6, argument_7, argument_8, )
> 

## Environment

 - PyTorch Version: 1.8.0
 - CPU Architecture: arm64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): .whl file for jetson
 - Build command you used (if compiling from source): `bazel build //:libtrtorch`
 - Are you using local sources or building from archives: Local
 - Python version: 3.7
 - CUDA version: 10.2
 - GPU models and configuration: Nvidia Jetson Xavier nx
 - Any other relevant information: torchvision C++ API compiled locally

## Additional context

I know that there is [batchedNMSPlugin](https://www.ccoderun.ca/programming/doxygen/tensorrt/md_TensorRT_plugin_batchedNMSPlugin_README.html) for TensorRT, but I have no idea how to include it for conversion. I'd appreciate any advice.

**Comment by narendasan** [comment]
I think we dont currently have an NMS converter, but it should be supportable in theory. The issue here is not with trtorch however. The issue is that NMS in pytorch is provided by torchvision as an extension. So you must make sure to load torchvision in your program. In the case of Python you can just import torchvision, in the case of C++ you need to link against the internal C++ library in torchvision. Here is some context on how to do that https://github.com/pytorch/vision/issues/2134 That should remove this issue and give you a TRTorch one saying the nms op doesnt have a converter. From that point you can follow the example of the GELU converter to create a converter that uses a TensorRT plugin https://github.com/NVIDIA/TRTorch/blob/03a6ca432ef34690fee25bd43c95bd7184530088/core/conversion/converters/impl/activation.cpp#L170

**Comment by VRSEN** [comment]
@narendasan thanks for such a quick reply, I got past that problem, however I am now stuck at 
`Unable to convert node: %151 : int = aten::Int(%150) (conversion.AddLayer)
Schema: aten::Int.Tensor(Tensor a) -> (int)
Converter for aten::Int requested, but no such converter was found`
I am trying to implement this converter myself but I am getting ITensor as an argument and I have no idea how to work with that. I would appreciate it if you could also give me a hint on how to convert ITensor to int and return it. Thanks

**Comment by maiskovich** [comment]
hi @VRSEN could you please provide some details of how did you manage to use batchedNMS with TensorRT?



Thank you

**Comment by VRSEN** [comment]
@maiskovich Sorry for my long silence.
I did this a while back and can't remember the process but I think this is the file you're looking for:
https://github.com/VRSEN/TRTorch/blob/d019ecf4f6f66d8d6cb02f89b104b902264d049c/core/conversion/converters/impl/nms.cpp
