### ISSUE TITLE
🐛 [Bug] Tuple input not supported

### ISSUE THREAD

**Issue by seed93** [NVIDIA/TRTorch#474]
##  Bug Description

tuple inputs not supported? version release v0.3.0

## To Reproduce

I use tuple and dict as inputs in submodule but not the main module. I also tried the torch_fallback feature, which did no help.

error trace as below:
```
~/.local/lib/python3.6/site-packages/trtorch/_compiler.py in compile(module, compile_spec)
     71             "torch.jit.ScriptFunction currently is not directly supported, wrap the function in a module to compile")
     72 
---> 73     compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
     74     compiled_module = torch.jit._recursive.wrap_cpp_module(compiled_cpp_mod)
     75     return compiled_module

RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::ListConstruct
```

**Comment by narendasan** [comment]
Can you provide the source graph or a example that replicates the issue? Seems like the error is coming from somewhere within PyTorch

**Comment by seed93** [comment]
```
import torch
import torch.nn as nn
from typing import Tuple, Dict, List
from torch import Tensor

class Model1(nn.Module):
    def __init__(self):
        super(Model1, self).__init__()
    def forward(self, inputs: Tuple[Tuple[Tensor], List[Tuple[Tensor, Tensor]]]):
        x, y = inputs
        return x, y

class ExportModel(nn.Module):
    def __init__(self, model):
        super(ExportModel, self).__init__()
        self.model = model
    def forward(self, x1, x2, x3):
        tuple_: Tuple[Tuple[Tensor], List[Tuple[Tensor, Tensor]]] = ((x1,), [(x2, x3)], )
        outputs = self.model(tuple_)
        return outputs[1]

export_model = ExportModel(Model1())
torch_script_module = torch.jit.script(export_model) 

input_list = [torch.tensor([[1,2,3]]), torch.tensor([[1,2,3]]), torch.tensor([[1,2,3]])]

result = torch_script_module(*input_list)

input_shape = []
for input in input_list:
    input_shape.append(input.shape)

compile_settings = {
    "input_shapes": input_shape,
    "op_precision": torch.float32, # Run with FP16,
    "torch_fallback" : {
      "enabled" : True,
      "min_block_size" : 1
    }
}
trt_ts_module = trtorch.compile(torch_script_module, compile_settings)
result = trt_ts_module(*input_list)
torch.jit.save(trt_ts_module, "trt_torchscript_module.ts")
```
The code above will cause this error

**Comment by narendasan** [comment]
Noticed a couple things with this issue. The root cause of the error you observed is because we run this lowering pass on the graph: https://github.com/pytorch/pytorch/blob/4cb534f92ef6f5b2ec99109b0329f93a859ae831/torch/csrc/jit/passes/lower_tuples.h#L15

It doesn't support graphs whose inputs contain tuples. 

If we switch to a less restrictive version of this pass we will get the same kind of issue as the other issue (#475) because the graph lowered graph is trivial: 

```
graph(%x1.1 : Tensor,
      %x2.1 : Tensor):
  %3 : (Tensor) = prim::TupleConstruct(%x2.1)
  %4 : (Tensor)[] = prim::ListConstruct(%3)
  return (%4)
(CompileGraph)
```

TRTorch wont do anything here, theres no operators for TensorRT to run. Again it would be good to have a less contrived example is its easier to see if the workflow you are looking for has some significant roadblock. As for tuple inputs they will be implemented with #428

**Comment by seed93** [comment]
So lets merge #475 here.
1. I make a simple example to reproduce my error, this is a simplified version. The original version would have an input like `Tuple[Tuple[Dict[str, Tensor], Dict[str, Dict[str, Tensor]]], Tensor, Tensor, Tensor, Tensor, List[Tuple[Tensor, Tensor]]]`. I cannot modify this complicated input.
2. I can run this model with torchscript smoothly but not trtorch. This makes me confused as I just think trtorch is a stronger torchscript compiler for nvidia gpu.
So can we cover these cases?

**Comment by narendasan** [comment]
TRTorch is a torchscript compiler but its subject to the limitations of TensorRT. So anything function run in TensorRT needs to take the form `func([Tensor]) -> [Tensor]`. We are working on allowing the compiler to reduce various groupings of Tensors to reduce to this form in #428. But the overarching limitation of TensorRT will still mean all inputs and outputs are Tensors. Things like Dicts are probably not going to be supported by TensorRT components. Partial compilation would be the method to potentially solve this but its still pretty unstable.
