### ISSUE TITLE
❓ [Question] How could I integrate TensorRT's Group Normalization plugin into a TRTorch model ? 

### ISSUE THREAD

**Issue by MatthieuTPHR** [NVIDIA/TRTorch#490]
## ❓ Question

What would be the steps to be able to use TensorRT's Group Normalization plugin into a TRTorch model ? 

The plugin is defined [here](https://github.com/NVIDIA/TensorRT/tree/master/plugin/groupNormalizationPlugin)

## Context

Being new to this, the Readme from core/conversion/converters didn't really clarify the steps I should follow to make the converter for a TensorRt plugin

## Environment

As an environment I use the `docker/Dockerfile.20.10 -t trtorch:pytorch1.7-cuda11.1-trt7.2.1` from the commit 6bb9fbf561c9cc3f0f1c4c7dde3d61c88e687efc

Thank you for your time and consideration

**Comment by peri044** [comment]
Please refer to README of https://github.com/NVIDIA/TRTorch/tree/master/core/plugins for integrating GN plugin. We also support Gelu plugin (from TensorRT) which is very similar to what you're trying with GN. Here's the Gelu example : https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/activation.cpp#L187
You can replace the plugin name with `GroupNormalizationPlugin` accordingly

**Comment by MatthieuTPHR** [comment]
Thank you very much !
