### ISSUE TITLE
✨[Feature] support for aten::is_floating_point

### ISSUE THREAD

**Issue by eslavaj** [NVIDIA/TRTorch#494]
**Hello I am trying to convert a pytorch model but one of operators is not supported. I tried to convert it like this:**

`
import torch
import torch.nn as nn
import trtorch

def main():

    model = torch.jit.load("/home/dvjes/orbslam3_WKSPC/deepslam/Examples/Monocular/gcn2_640x480.pt")

    scripted_model = torch.jit.script(model)

    compile_settings = {
    "input_shapes": [[1, 1, 480, 640]],
    "op_precision": torch.float32
    }

    trt_ts_module = trtorch.compile(scripted_model, compile_settings)
    torch.jit.save(trt_ts_module, 'gcnv2_480_640_trtorch.jit')

if __name__ == "__main__":
    main()
`

-------------------------------------------

**When executing the above script I got the following error:**

ERROR: [TRTorch] - Requested converter for aten::is_floating_point, but no such converter was found
Traceback (most recent call last):
  File "test_convert_trtorch.py", line 22, in <module>
    main()
  File "test_convert_trtorch.py", line 18, in main
    trt_ts_module = trtorch.compile(scripted_model, compile_settings)
  File "/usr/local/lib/python3.6/dist-packages/trtorch/_compiler.py", line 73, in compile
    compiled_cpp_mod = trtorch._C.compile_graph(module._c, _parse_compile_spec(compile_spec))
RuntimeError: [Error thrown at core/conversion/conversion.cpp:113] Expected converter to be true but got false
Unable to convert node: %53 : bool = aten::is_floating_point(%input_16.1) # <string>:3:6 (conversion.AddLayer)
Schema: aten::is_floating_point(Tensor self) -> (bool)
Converter for aten::is_floating_point requested, but no such converter was found.
If you need a converter for this operator, you can try implementing one yourself
or request a converter: https://www.github.com/NVIDIA/TRTorch/issues

Is there any plan to add this converter?

Thanks.

**Comment by narendasan** [comment]
We will probably add support for this as part of our casting efforts https://github.com/NVIDIA/TRTorch/discussions/412 cc: @peri044

**Comment by narendasan** [comment]
This is supported in v0.4.0
