### ISSUE TITLE
🐛 [Bug] Quantization fails with Dataset that does not implement `data` attribute

### ISSUE THREAD

**Issue by Belval** [NVIDIA/TRTorch#498]
##  Bug Description

When using PTQ in Python, using a custom DataLoader/Dataset will raise an exception. This is caused by the absence of the attribute `data` which does not seem to be standard PyTorch.

## To Reproduce

I have not come up with a reproducible test case that I can share, however I can provide the exact lines causing the issue in PyTorch and TRTorch.

- Usage of `torch.utils.data.Dataset.data`: https://github.com/NVIDIA/TRTorch/blob/master/py/trtorch/ptq.py#L29
- Definition of `torch.utils.data.Dataset` which shows the absence of that attribute: https://github.com/pytorch/pytorch/blob/master/torch/utils/data/dataset.py#L17

```
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  AttributeError: 'MyCustomDatasetWhichInheritsFromDataset' object has no attribute 'data'

At:
  /home/ubuntu/env/lib/python3.7/site-packages/trtorch/ptq.py(29): get_batch
  /home/ubuntu/env/lib/python3.7/site-packages/trtorch/_compiler.py(73): compile
  eval.py(75): optimize_model
  eval.py(319): eval
  eval.py(166): main
  eval.py(451): <module>

```

## Expected behavior

Instead of doing Dataset.data.shape[0] to get what I assume is the number of samples, you can use `len(dataset)` which should return the correct number.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - TRTorch Version (e.g. 0.2.0): 0.4.0a0 (built from source)
 - PyTorch Version (e.g. 1.0): 1.8.1
 - CPU Architecture: x86_64
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): pip
 - Build command you used (if compiling from source): `python3 setup.py install`
 - Are you using local sources or building from archives: local
 - Python version: 3.7
 - CUDA version: 11.1
 - GPU models and configuration: Nvidia T4
 - Any other relevant information: N/A

**Comment by peri044** [comment]
Thanks @Belval  https://github.com/NVIDIA/TRTorch/pull/504 fixes this.
