### ISSUE TITLE
❓ [Question] How can I trace the code that causing Unsupported operators

### ISSUE THREAD

**Issue by lamhoangtung** [NVIDIA/TRTorch#511]
## ❓ Question

Hi. I'm trying to enable TensorRT for a Torch Script model and getting a bunch of Unsupported operators. I'm willing to change the implementation to avoid those unsupported operators or even trying to add support for it. But I struggling to find which line of code in my model are causing it.

I'm doing something like this:
```python
model = torch.jit.script(model)
model = torch._C._jit_to_backend("tensorrt", model, spec)
```

And getting something like this:
```console
ERROR: [TRTorch] - Method requested cannot be compiled by TRTorch.
Unsupported operators listed below:
  -  aten::__contains__.str_list(str[] l, str item) -> (bool)
  -  aten::_set_item.str(Dict(str, t)(a!) l, str(b -> *) idx, t(c -> *) v) -> ()
  -  aten::dict() -> (Dict(str, Tensor))
  -  aten::format(str self, ...) -> (str)
  -  aten::list.t(t[] l) -> (t[])
  -  aten::values.str(Dict(str, t) self) -> (t[](*))
You can either implement converters for these ops in your application or request implementation
https://www.github.com/nvidia/TRTorch/issues

Traceback (most recent call last):
  File "convert.py", line 6, in <module>
    model = SomeModel('weights/ghostnet0.5.pth')
  File "/home/linus/model/model.py", line 88, in __init__
    self.model = torch._C._jit_to_backend("tensorrt", self.model, spec)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 4, in __preprocess
            def __preprocess(self, mod: Any, method_compile_spec: Dict[str, Any]):
                self.__create_backend()
                self.__processed_module = self.__backend.preprocess(mod, method_compile_spec)
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
          
RuntimeError: [enforce fail at /workspace/TRTorch/py/trtorch/csrc/tensorrt_backend.cpp:19] Expected core::CheckMethodOperatorSupport(mod.toModule(), it->key()) to be true but got false
Method forwardcannot be compiled by TRTorch
```

My question is:
- Does TRTorch have some traceback (like TorchScript) to tell the users which line of code caused the problem ?
- How can I find which line of code are using the unsupported operations?

## What you have already tried
I have tried printing out the graph for my scripted model with: `print(model.graph)` but yet to find those listed operators above.
```
graph(%self : __torch__.retinaface.RetinaFace,
      %inputs.1 : Tensor):
  %124 : Function = prim::Constant[name="softmax"]()
  %123 : None = prim::Constant()
  %122 : int = prim::Constant[value=3]()
  %121 : int = prim::Constant[value=-1]() # /home/linus/model/model.py:121:67
  %index.1 : int = prim::Constant[value=0]() # /home/linus/model/model.py:98:33
  %index.3 : int = prim::Constant[value=1]() # /home/linus/model/model.py:99:33
....
```

I thought that by finding the ops, I can use that comment on the right to find which part of my code are using an unsupported ops. But so far, none have been found ;(

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.0): 1.8.1
 - CPU Architecture: x86
 - OS (e.g., Linux): Ubuntu 20.04 LTS
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): conda
 - Build command you used (if compiling from source): None
 - Are you using local sources or building from archives: local sources
 - Python version: 3.8.8
 - CUDA version: 11.1.74
 - GPU models and configuration: GTX 1080Ti
 - Any other relevant information: 

## Additional context

None for now. Thanks for checking by ;)

**Comment by narendasan** [comment]
We dont have a traceback feature like TorchScript since from the perspective of TRTorch, the Python source doesn't exist. The operator names can give hints as to where in the code you are getting caught. Here it looks like you are getting caught on Dictionary operations, List operations like maybe you have a `if x in list_` in your code somewhere and it seems like a print statement as well for `aten::format`. Dictionaries in particular are difficult to support in TRTorch, if you can avoid using them that will give you the best chance for full compilation otherwise it might be good to try the partial compilation feature.

**Comment by lamhoangtung** [comment]
Thanks for the reply @narendasan.

While I was printing the `scripted_model.graph`:
```
%121 : int = prim::Constant[value=-1]() # /home/linus/model/model.py:121:67
```
I noticed the comment on the right indicate that this node was in `model.py` file at line `127:67`. Do you thinks that TRTorch can somehow use this information and give a rough estimate of where the code was broken ? If yes, do you thinks it is hard to implement? I can try to help with a PR but I need to know how to map each ops to a node like `%121` in the example above

**Comment by narendasan** [comment]
It might be nice to pull out these comments to provide additional context to the user. I dont remember exactly how these comments are stored, but I assume that its some attribute of the particular node. I think if you can find it, you just need to slightly modify these error messages https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/conversion.cpp. You could probably make a utility function in `//core/util/jit_util.h` that takes a node and returns the comment. Should not be too hard. Here is some relevant documentation for how information is stored in nodes https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/OVERVIEW.md

**Comment by lamhoangtung** [comment]
Thanks for the reply @narendasan. Will look into it and get back latter ;)

**Comment by lamhoangtung** [comment]
I've submitted a PR(#521). Can you take a look @narendasan ?
