### ISSUE TITLE
✨[Feature] Let users set input shape, dtype and format using example tensors

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#514]
**Is your feature request related to a problem? Please describe.**

Now that we are going to be able to specify tensor properties for inputs such as data type and format, it should be easier to use a tensor I already have as an example of the shape dtype and format I want.

**Describe the solution you'd like**

compile should be able to accept a list of Tensors to represent my graph inputs. From those tensors compile should be able to infer shape, data type and tensor format for the user. These should be logged in the debug log for easy debugging. 

**Describe alternatives you've considered**

Note: I dont think theres a way to support dynamic shape using this method, so users will need to use `trtorch.Input` for that 

**Additional context**

**Comment by borisfom** [comment]
Why, if you supply 3 Tensors for min/opt/max, it's no less flexibility than we have with size arguments.

**Comment by borisfom** [comment]
This also correlates with https://github.com/NVIDIA/TRTorch/issues/538

**Comment by narendasan** [comment]
> Why, if you supply 3 Tensors for min/opt/max, it's no less flexibility than we have with size arguments.

There are some issues I see with defining min/opt/max with example tensors, at least how i pictured it. For instance: 

```py
trtorch.compile(my_mod, {"inputs": [example_in]})
```
From `example_in` we can infer shape, dtype and tensor format directly from the Tensor.

In the case of dynamic shape, we need some sort of grouping for the tensor, so maybe you do something like 

```py
trtorch.compile(my_mod, {"inputs": [
    {"min": example_in_min, 
     "opt": example_in_opt, 
     "max": example_in_max}
]})
``` 
But, in this case, what do we do if something like the dtype or tensor format is inconstant between tensors? 
Also doesnt seem like this is that different than doing at this point: 

```py
trtorch.compile(my_mod, {"inputs": [
    trtorch.Input(min_shape=example_in_min.shape(), 
        opt_shape=example_in_opt.shape(), 
        max_shape=example_in_max.shape(), dtype=torch.float)
]})
``` 
We could maybe have `trtorch.Input` pull out the shape and error out if the types are inconstant. Really though we wanted to give users a bypass around `trtorch.Input` with this feature.
