### ISSUE TITLE
TRTorch (both CLI and Python) should accept user-supplied content for inputs, not just dimensions.

### ISSUE THREAD

**Issue by borisfom** [NVIDIA/TRTorch#538]
**Is your feature request related to a problem? Please describe.**
not all nets are able to run on random inputs. There are nets where an input contains indices into another input / internal table - those nave to be integers in particular range, not random values for network to even not crash.
Though compile process only needs dimensions, post-compile verification may require user-supplied values.

**Describe the solution you'd like**
Polygraphy tool, for example, has an option to supply input values from files.

**Describe alternatives you've considered**

**Additional context**

**Comment by narendasan** [comment]
Do you know if theres a way to serialize just tensors? pickling would work well for python but not C++ or the CLI, im not sure if torchscript lets you do this.

**Comment by narendasan** [comment]
Seems like torch provides a pickle_load function we could use here https://github.com/pytorch/pytorch/issues/20356#issuecomment-567663701
