### ISSUE TITLE
❓ [Question] How can i get libtrtorchrt.so? 

### ISSUE THREAD

**Issue by JuncFang-git** [NVIDIA/TRTorch#562]
## ❓ Question

Thanks for your contribution. 
I can't get the "libtrtorchrt.so" described in the following document after completing the trtorch. So, how can I get it?
![image](https://user-images.githubusercontent.com/76929740/128478080-d7ba65c1-413e-4072-88bf-972daf826fe8.png)

## What you have already tried

 complete the trtorch as the github guide

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version ( 1.8.1):
 - OS ( Linux):
 - How you installed PyTorch (`pip`, `libtorch`):
 - Build command you used (bazel build //:libtrtorch -c opt):
 - Python version: 3.8
 - CUDA version: 11.3
 - GPU models and configuration: GTX3070

**Comment by peri044** [comment]
When you build TRTorch with `bazel build //:libtrtorch -c opt`, the generated `bazel-bin/libtrtorch.tar.gz` should contain `libtrtorchrt.so` in `lib` directory. Alternatively, you can find runtime library in the pre-built releases as well 
https://github.com/NVIDIA/TRTorch/releases/download/v0.3.0/libtrtorch-v0.3.0-cudnn8.1-tensorrt7.2-cuda11.1-libtorch-1.8.1.tar.gz

**Comment by JuncFang-git** [comment]
> When you build TRTorch with `bazel build //:libtrtorch -c opt`, the generated `bazel-bin/libtrtorch.tar.gz` should contain `libtrtorchrt.so` in `lib` directory. Alternatively, you can find runtime library in the pre-built releases as well
> https://github.com/NVIDIA/TRTorch/releases/download/v0.3.0/libtrtorch-v0.3.0-cudnn8.1-tensorrt7.2-cuda11.1-libtorch-1.8.1.tar.gz

Nice!
