### ISSUE TITLE
❓ [Question] How can i build a Makefile for this example? 

### ISSUE THREAD

**Issue by JuncFang-git** [NVIDIA/TRTorch#566]
## ❓ Question
Hi, 
I want to run the official [example ](https://github.com/NVIDIA/TRTorch/blob/master/examples/sample_rt_app/main.cpp) with a Makefile. But there is always something wrong. So, could you give me the Makefile that successfully links to the .so file?

## Environment

 - PyTorch Version (1.8):
 - OS (Ubuntu18.04):
 - How you installed PyTorch (`pip`, `libtorch`)
 - Python version: 3.8
 - CUDA version: 11.3
 - GPU models and configuration: GTX3070

**Comment by narendasan** [comment]
@JuncFang-git take a look at #569

**Comment by JuncFang-git** [comment]
> @JuncFang-git take a look at #569

Nice job!
But as for me, --no-as-needed xxxx "-lbackend_with_compiler" make some errors, it works when I remove it. I don't know what does this parameter means?

**Comment by narendasan** [comment]
You need no-as-needed to link libtrtorchrt.so since there is no source code dependency and it won't be linked otherwise

**Comment by JuncFang-git** [comment]
> You need no-as-needed to link libtrtorchrt.so since there is no source code dependency and it won't be linked otherwise

I can't link the lib of "backend_with_compiler", so I remove it and it works. Does this cause any problems?
