### ISSUE TITLE
❓ [Question] How to build latest TRTorch with Pytorch 1.9.0

### ISSUE THREAD

**Issue by raju-tapway** [NVIDIA/TRTorch#575]
## ❓ Question

I am trying to build latest TRTorch with Torch 1.9.0 but I am getting some issue. I follow the instruction from [here](https://github.com/NVIDIA/TRTorch/blob/master/README.md)

Also followed https://nvidia.github.io/TRTorch/tutorials/installation.html but not able to build. Please help!
## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version: `1.9.0`
 - CPU Architecture: `x86_64`
 - OS: `Linux` (Ubuntu 18.04)
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `pip` from [here](https://pytorch.org/get-started/locally/)
 - Build command you used (if compiling from source):  `bazel build //:libtrtorch --compilation_mode opt` and `cd py && sudo python3.7 setup.py install`
 - Are you using local sources or building from archives: `local`
 - Python version: `3.7`
 - CUDA version: `11.1`
 - CUDNN version: `8.1`
 - TensorRT: `7.2.3.4`
 - Bazel: `4.0.0`
 - GPU models and configuration: `RTX 2070 super 8GB`
 - Any other relevant information:

## Additional context
Attached the error I got while I run `bazel build //:libtrtorch --compilation_mode opt` or `cd py && sudo python3.7 setup.py install`
```
user@test ~/Documents/TRTorch/py
 └─ (master) $ sudo python3.7 setup.py install
running install
building libtrtorch
INFO: Analyzed target //cpp/api/lib:libtrtorch.so (18 packages loaded, 2249 targets configured).
INFO: Found 1 target...
ERROR: /home/user/Documents/TRTorch/core/lowering/passes/BUILD:10:11: Compiling core/lowering/passes/op_aliasing.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./core/util/prelude.h:10:0,
                 from core/lowering/passes/op_aliasing.cpp:3:
./core/util/trt_util.h: In function 'std::ostream& nvinfer1::operator<<(std::ostream&, const nvinfer1::EngineCapability&)':
./core/util/trt_util.h:90:38: error: 'kSTANDARD' is not a member of 'nvinfer1::EngineCapability'
     case nvinfer1::EngineCapability::kSTANDARD:
                                      ^~~~~~~~~
./core/util/trt_util.h:92:38: error: 'kSAFETY' is not a member of 'nvinfer1::EngineCapability'
     case nvinfer1::EngineCapability::kSAFETY:
                                      ^~~~~~~
./core/util/trt_util.h:94:38: error: 'kDLA_STANDALONE' is not a member of 'nvinfer1::EngineCapability'
     case nvinfer1::EngineCapability::kDLA_STANDALONE:
                                      ^~~~~~~~~~~~~~~
Target //cpp/api/lib:libtrtorch.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.640s, Critical Path: 6.17s
INFO: 8 processes: 8 internal.
FAILED: Build did NOT complete successfully
```

Workspace modified file: 
```
workspace(name = "TRTorch")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

http_archive(
    name = "rules_python",
    sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
)

load("@rules_python//python:pip.bzl", "pip_install")

http_archive(
    name = "rules_pkg",
    sha256 = "038f1caa773a7e35b3663865ffb003169c6a71dc995e39bf4815792f385d837d",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

git_repository(
    name = "googletest",
    commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
    remote = "https://github.com/google/googletest",
    shallow_since = "1570114335 -0400",
)

# CUDA should be installed on the system locally
new_local_repository(
    name = "cuda",
    build_file = "@//third_party/cuda:BUILD",
    path = "/usr/local/cuda-11.1/",
)

new_local_repository(
    name = "cublas",
    build_file = "@//third_party/cublas:BUILD",
    path = "/usr",
)
#############################################################################################################
# Tarballs and fetched dependencies (default - use in cases when building from precompiled bin and tarballs)
#############################################################################################################


# Download these tarballs manually from the NVIDIA website
# Either place them in the distdir directory in third_party and use the --distdir flag
# or modify the urls to "file:///<PATH TO TARBALL>/<TARBALL NAME>.tar.gz



####################################################################################
# Locally installed dependencies (use in cases of custom dependencies or aarch64)
####################################################################################

# NOTE: In the case you are using just the pre-cxx11-abi path or just the cxx11 abi path
# with your local libtorch, just point deps at the same path to satisfy bazel.

# NOTE: NVIDIA's aarch64 PyTorch (python) wheel file uses the CXX11 ABI unlike PyTorch's standard
# x86_64 python distribution. If using NVIDIA's version just point to the root of the package
# for both versions here and do not use --config=pre-cxx11-abi

new_local_repository(
    name = "libtorch",
    path = "/usr/local/lib/python3.7/dist-packages/torch",
    build_file = "third_party/libtorch/BUILD"
)

new_local_repository(
    name = "libtorch_pre_cxx11_abi",
    path = "/usr/local/lib/python3.7/dist-packages/torch",
    build_file = "third_party/libtorch/BUILD"
)

new_local_repository(
    name = "cudnn",
    path = "/usr/",
    build_file = "@//third_party/cudnn/local:BUILD"
)

new_local_repository(
   name = "tensorrt",
   path = "/usr/",
   build_file = "@//third_party/tensorrt/local:BUILD"
)

#########################################################################
# Testing Dependencies (optional - comment out on aarch64)
#########################################################################
pip_install(
    name = "trtorch_py_deps",
    requirements = "//py:requirements.txt",
)

pip_install(
    name = "py_test_deps",
    requirements = "//tests/py:requirements.txt",
)

pip_install(
    name = "pylinter_deps",
    requirements = "//tools/linter:requirements.txt",
)
```

**Comment by JuncFang-git** [comment]
> ## ❓ Question
> I am trying to build latest TRTorch with Torch 1.9.0 but I am getting some issue. I follow the instruction from [here](https://github.com/NVIDIA/TRTorch/blob/master/README.md)
> 
> Also followed https://nvidia.github.io/TRTorch/tutorials/installation.html but not able to build. Please help!
> 
> ## What you have already tried
> ## Environment
> > Build information about the TRTorch compiler can be found by turning on debug messages
> 
> * PyTorch Version: `1.9.0`
> * CPU Architecture: `x86_64`
> * OS: `Linux` (Ubuntu 18.04)
> * How you installed PyTorch (`conda`, `pip`, `libtorch`, source): `pip` from [here](https://pytorch.org/get-started/locally/)
> * Build command you used (if compiling from source):  `bazel build //:libtrtorch --compilation_mode opt` and `cd py && sudo python3.7 setup.py install`
> * Are you using local sources or building from archives: `local`
> * Python version: `3.7`
> * CUDA version: `11.1`
> * CUDNN version: `8.1`
> * TensorRT: `7.2.3.4`
> * Bazel: `4.0.0`
> * GPU models and configuration: `RTX 2070 super 8GB`
> * Any other relevant information:
> 
> ## Additional context
> Attached the error I got while I run `bazel build //:libtrtorch --compilation_mode opt` or `cd py && sudo python3.7 setup.py install`
> 
> ```
> user@test ~/Documents/TRTorch/py
>  └─ (master) $ sudo python3.7 setup.py install
> running install
> building libtrtorch
> INFO: Analyzed target //cpp/api/lib:libtrtorch.so (18 packages loaded, 2249 targets configured).
> INFO: Found 1 target...
> ERROR: /home/user/Documents/TRTorch/core/lowering/passes/BUILD:10:11: Compiling core/lowering/passes/op_aliasing.cpp failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox
> In file included from ./core/util/prelude.h:10:0,
>                  from core/lowering/passes/op_aliasing.cpp:3:
> ./core/util/trt_util.h: In function 'std::ostream& nvinfer1::operator<<(std::ostream&, const nvinfer1::EngineCapability&)':
> ./core/util/trt_util.h:90:38: error: 'kSTANDARD' is not a member of 'nvinfer1::EngineCapability'
>      case nvinfer1::EngineCapability::kSTANDARD:
>                                       ^~~~~~~~~
> ./core/util/trt_util.h:92:38: error: 'kSAFETY' is not a member of 'nvinfer1::EngineCapability'
>      case nvinfer1::EngineCapability::kSAFETY:
>                                       ^~~~~~~
> ./core/util/trt_util.h:94:38: error: 'kDLA_STANDALONE' is not a member of 'nvinfer1::EngineCapability'
>      case nvinfer1::EngineCapability::kDLA_STANDALONE:
>                                       ^~~~~~~~~~~~~~~
> Target //cpp/api/lib:libtrtorch.so failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 8.640s, Critical Path: 6.17s
> INFO: 8 processes: 8 internal.
> FAILED: Build did NOT complete successfully
> ```
> 
> Workspace modified file:
> 
> ```
> workspace(name = "TRTorch")
> 
> load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
> load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
> 
> http_archive(
>     name = "rules_python",
>     sha256 = "778197e26c5fbeb07ac2a2c5ae405b30f6cb7ad1f5510ea6fdac03bded96cc6f",
>     url = "https://github.com/bazelbuild/rules_python/releases/download/0.2.0/rules_python-0.2.0.tar.gz",
> )
> 
> load("@rules_python//python:pip.bzl", "pip_install")
> 
> http_archive(
>     name = "rules_pkg",
>     sha256 = "038f1caa773a7e35b3663865ffb003169c6a71dc995e39bf4815792f385d837d",
>     urls = [
>         "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
>         "https://github.com/bazelbuild/rules_pkg/releases/download/0.4.0/rules_pkg-0.4.0.tar.gz",
>     ],
> )
> 
> load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")
> 
> rules_pkg_dependencies()
> 
> git_repository(
>     name = "googletest",
>     commit = "703bd9caab50b139428cea1aaff9974ebee5742e",
>     remote = "https://github.com/google/googletest",
>     shallow_since = "1570114335 -0400",
> )
> 
> # CUDA should be installed on the system locally
> new_local_repository(
>     name = "cuda",
>     build_file = "@//third_party/cuda:BUILD",
>     path = "/usr/local/cuda-11.1/",
> )
> 
> new_local_repository(
>     name = "cublas",
>     build_file = "@//third_party/cublas:BUILD",
>     path = "/usr",
> )
> #############################################################################################################
> # Tarballs and fetched dependencies (default - use in cases when building from precompiled bin and tarballs)
> #############################################################################################################
> 
> 
> # Download these tarballs manually from the NVIDIA website
> # Either place them in the distdir directory in third_party and use the --distdir flag
> # or modify the urls to "file:///<PATH TO TARBALL>/<TARBALL NAME>.tar.gz
> 
> 
> 
> ####################################################################################
> # Locally installed dependencies (use in cases of custom dependencies or aarch64)
> ####################################################################################
> 
> # NOTE: In the case you are using just the pre-cxx11-abi path or just the cxx11 abi path
> # with your local libtorch, just point deps at the same path to satisfy bazel.
> 
> # NOTE: NVIDIA's aarch64 PyTorch (python) wheel file uses the CXX11 ABI unlike PyTorch's standard
> # x86_64 python distribution. If using NVIDIA's version just point to the root of the package
> # for both versions here and do not use --config=pre-cxx11-abi
> 
> new_local_repository(
>     name = "libtorch",
>     path = "/usr/local/lib/python3.7/dist-packages/torch",
>     build_file = "third_party/libtorch/BUILD"
> )
> 
> new_local_repository(
>     name = "libtorch_pre_cxx11_abi",
>     path = "/usr/local/lib/python3.7/dist-packages/torch",
>     build_file = "third_party/libtorch/BUILD"
> )
> 
> new_local_repository(
>     name = "cudnn",
>     path = "/usr/",
>     build_file = "@//third_party/cudnn/local:BUILD"
> )
> 
> new_local_repository(
>    name = "tensorrt",
>    path = "/usr/",
>    build_file = "@//third_party/tensorrt/local:BUILD"
> )
> 
> #########################################################################
> # Testing Dependencies (optional - comment out on aarch64)
> #########################################################################
> pip_install(
>     name = "trtorch_py_deps",
>     requirements = "//py:requirements.txt",
> )
> 
> pip_install(
>     name = "py_test_deps",
>     requirements = "//tests/py:requirements.txt",
> )
> 
> pip_install(
>     name = "pylinter_deps",
>     requirements = "//tools/linter:requirements.txt",
> )
> ```

Hi, 
Your TensorRT version is not suited to build the master branch. "kSTANDARD", "kSAFETY" ...  can be found at [TensorRT8.0.x](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a0a816406cdb5bff7c1ab299d8e58e8d2) but not [TensoRT7.2.3.4](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-723/api/c_api/namespacenvinfer1.html#a0a816406cdb5bff7c1ab299d8e58e8d2) .

So, maybe it works when you update your TensorRT.
I am also interested in the latest TRTorch,  Hope you can reply to me if you make it works.

**Comment by JuncFang-git** [comment]
Hi,
Your TensorRT version is not suited to build the master branch. "kSTANDARD", "kSAFETY" ... can be found at [TensorRT8.0.x](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#a0a816406cdb5bff7c1ab299d8e58e8d2) but not [TensoRT7.2.3.4](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-723/api/c_api/namespacenvinfer1.html#a0a816406cdb5bff7c1ab299d8e58e8d2) .

So, maybe it works when you update your TensorRT.
I am also interested in the latest TRTorch, Hope you can reply to me if you make it works.

**Comment by narendasan** [comment]
Yeah, likely the issue is that you are using using TensorRT 7.x. The master branch targets TensorRT 8.0. Do you require support for 7.x?

**Comment by raju-tapway** [comment]
Thanks @JuncFang-git @narendasan for your kind reply. I upgraded tensorrt version from 7.2 to `8.0` and Cudnn version from 8.1 to `8.2` and then build again. TRTorch is successfully build now.

```
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import trtorch
>>> trtorch.__version__
'0.4.0a0'
```

Note: I will close the issue once I fully tested the latest TRTorch.
