### ISSUE TITLE
❓ [Question] How can i write a converter just use a Libtorch function? 

### ISSUE THREAD

**Issue by JuncFang-git** [NVIDIA/TRTorch#576]
## ❓ Question

Hi,
I am trying to write some converter like "torch.inverse", "F.grid_sample", but it's really difficult for me. So, I want to skip that using just some libtorch function.
For example, I want to build a converter just use torch::inverse.
![image](https://user-images.githubusercontent.com/76929740/129295419-43256861-c4a9-4f5f-a0fc-345cf01df7e0.png)
But I got some errors like this :
![image](https://user-images.githubusercontent.com/76929740/129295506-b48255a1-4ce4-4511-8786-642f8a8072e3.png)

So, how can i write a converter just use a Libtorch function? 

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (1.8.1):
 - OS (ubuntu18.04):
 - How you installed PyTorch ( `pip`, `libtorch`):
 - Build command you used (trtorchv0.3.0 form release):
 - Python version: 3.8
 - CUDA version: 11.1
 - GPU models and configuration:GTX3070

**Comment by JuncFang-git** [comment]
Any response？

**Comment by narendasan** [comment]
Take a look at 

https://github.com/NVIDIA/TRTorch/blob/master/core/conversion/converters/impl/interpolate.cpp
https://github.com/NVIDIA/TRTorch/blob/master/core/plugins/impl/interpolate_plugin.cpp
