### ISSUE TITLE
❓ memcpy d2d occupies a lot time of inference  (resnet50 model  after trtorch)

### ISSUE THREAD

**Issue by chunhuagod** [NVIDIA/TRTorch#579]
## What you have already tried
I use trtorch to optimize resnet50 model on the IMAGENET as follows
<img width="998" alt="截屏2021-08-16 10 34 32" src="https://user-images.githubusercontent.com/46394627/129503893-4d252f02-07d4-448a-ac9c-7f64f15aa30a.png">
 Unfortunately, i found that the memcpy d2d occupies a lot time of inference when i'm testing the performance of optimized model
<img width="1420" alt="截屏2021-08-16 10 23 43" src="https://user-images.githubusercontent.com/46394627/129504130-66f60eae-d9eb-4384-bcbd-53c6e83f4d0e.png">
In the above figure, we can observe that the memcpy d2d occurs at the beginning of the inference and result in about 10% time consumption. I haven't found the reason yet. I did not have this phenomenon when I used tensorrt engine.

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - PyTorch Version (e.g., 1.6.0):
 - OS (e.g., Linux):linux
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source):pip
 - Python version:3.6.0
 - CUDA version:10.0
 - GPU models and configuration:T4*1 16G

**Comment by narendasan** [comment]
What version of TRTorch are you using? Do you see any warnings about D2D copies coming from the runtime?

**Comment by chunhuagod** [comment]
> What version of TRTorch are you using? Do you see any warnings about D2D copies coming from the runtime?

I'm using the TRTorch v0.2.0 and I didn't found any warning when executing the model inference.

**Comment by narendasan** [comment]
Can you try using the latest version on master? There are new parts of the runtime which will check for the need to move input tensors between devices and will let you know if it does

**Comment by chunhuagod** [comment]
thx, the problem didn't occur when i try version0.3.0.
