### ISSUE TITLE
❓ [Question] How to convert nvinfer1::ITensor into at::tensor?

### ISSUE THREAD

**Issue by JuncFang-git** [NVIDIA/TRTorch#580]
## ❓ Question
Hi, 
How to convert nvinfer1::ITensor into at::tensor?   Like   #146 

## What you have already tried

I want to do some operations use libtorch on the nvinfer1::ITensor. So, can I convert nvinfer1::ITensor into at::tensor? Or I must write a custom converter with the libtorch function?
@xsacha @aaronp24 @itsliupeng @lukeyeager @elezar

**Comment by narendasan** [comment]
You cant really convert ITensors into at::Tensors, ITensors are just edges between layers in the tensorrt and have no concrete value. You can set that ITensor as an output and feed it to some Torch code outside of the TRTorch program
