### ISSUE TITLE
❓ [Question] module 'trtorch' has no attribute 'Input'

### ISSUE THREAD

**Issue by gaosanyuan** [NVIDIA/TRTorch#596]
Why the installed trtorch has no attribute 'Input'? Thanks
trtorch version: 0.3.0

**Comment by narendasan** [comment]
Input is added in TRTorch v0.4.0. In TRTorch v0.3.0 you pass in the shapes as tuples or dicts https://nvidia.github.io/TRTorch/v0.3.0/tutorials/getting_started.html#compiling-with-trtorch-in-python

**Comment by narendasan** [comment]
(moving to discussions as it seems to be mostly a usage question)
