### ISSUE TITLE
🐛 [libtorch_cuda_cu.so: cannot open shared object file: No such file or directory] Encountered bug when using TRTorch

### ISSUE THREAD

**Issue by shiyongming** [NVIDIA/TRTorch#624]
## To Reproduce

1. docker run --rm -it --gpus '"device=1"' -v ~:/workspace/hostdir nvcr.io/nvidia/pytorch:21.08-py3
2. pip3 install trtorch -f https://github.com/NVIDIA/TRTorch/releases
3. import trtorch

## Environment

> Build information about the TRTorch compiler can be found by turning on debug messages

 - TRTorch Version (e.g. 0.2.0): 0.4.0
 - PyTorch Version (e.g. 1.0): 1.9.0
 - CPU Architecture: T4
 - OS: Ubuntu1804
 - How you installed PyTorch (`conda`, `pip`, `libtorch`, source): NGC docker image
 - Build command you used (if compiling from source):
 - Are you using local sources or building from archives:
 - Python version: 3.8.10
 - CUDA version: 11.4
 - GPU models and configuration:
 - Any other relevant information:

**Comment by narendasan** [comment]
The PyTorch NGC container uses a different version of PyTorch than the standard distribution in a couple of ways that make installing from the wheels not work. It uses a different ABI than the PyTorch from pytorch.org and it also uses a newer build (master branch around July - Aug) than the target version of PyTorch for the wheel file (PyTorch 1.9). I suggest building from source in the container. In the future we are looking to distribute TRTorch with the container so you wont have to worry about this.

**Comment by shiyongming** [comment]
Got it. Thank you @narendasan !
