### ISSUE TITLE
TRTorch with CUDA 10.0

### ISSUE THREAD

**Issue by esghif** [NVIDIA/TRTorch#68]
Hi, 

I tried installing TRTorch on my Ubuntu 16.04, PyTorch 1.5 compiled from source, CUDA 10.0, CUDNN 7.6.

I am getting a symbol error in all configurations I tried. I am grateful for any help.

`seh2bp@trtorch:/workspace$ python -c "import torch; import trtorch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 165, in <module>
    from torch._C import *
ImportError: /opt/conda/lib/python3.7/site-packages/torch/lib/libshm.so: undefined symbol: _Z8_THErrorPKciS0_z`

ldd output is here:

`seh2bp@trtorch:/workspace$ ldd /opt/conda/lib/python3.7/site-packages/trtorch/lib/libtrtorch.so
        linux-vdso.so.1 (0x00007ffdff3c7000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f338cc4d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f338c8af000)
        libnvinfer.so.7 => /opt/tensorrt/TensorRT-7.0.0.11/lib/libnvinfer.so.7 (0x00007f337ec34000)
        libcublas.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcublas.so.10.0 (0x00007f337a69e000)
        libcudnn.so.7 => /usr/lib/x86_64-linux-gnu/libcudnn.so.7 (0x00007f3362e8d000)
        libtorch.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libtorch.so (0x00007f3362c8b000)
        libtorch_cuda.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libtorch_cuda.so (0x00007f33211cc000)
        libtorch_cpu.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libtorch_cpu.so (0x00007f3311fae000)
        libtorch_global_deps.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libtorch_global_deps.so (0x00007f3311da9000)
        libc10_cuda.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libc10_cuda.so (0x00007f3311b73000)
        libc10.so => /workspace/scer-docker/trtorch/files/libtorch/lib/libc10.so (0x00007f3311923000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f331170b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f331131a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f338cfd6000)
        libcudart.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudart.so.10.0 (0x00007f33110a0000)
        libmyelin.so.1 => /opt/tensorrt/TensorRT-7.0.0.11/lib/libmyelin.so.1 (0x00007f331088f000)
        libnvrtc.so.10.0 => /usr/local/cuda-10.0/targets/x86_64-linux/lib/libnvrtc.so.10.0 (0x00007f330f273000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f330f06f000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f330ee50000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f330ec48000)
        libcudart-80664282.so.10.2 => /workspace/scer-docker/trtorch/files/libtorch/lib/libcudart-80664282.so.10.2 (0x00007f330e9c7000)
        libnvToolsExt-3965bdd0.so.1 => /workspace/scer-docker/trtorch/files/libtorch/lib/libnvToolsExt-3965bdd0.so.1 (0x00007f330e7bd000)
        libgomp-75eea7e8.so.1 => /workspace/scer-docker/trtorch/files/libtorch/lib/libgomp-75eea7e8.so.1 (0x00007f330e598000)`

I tried different configurations:

- use the downloaded libtorch built for cuda 10.2, I get the same error as above
- use the installed libtorch (for a reason I don't understand I have 2 versions on in 
`.../site-packages/torch` and one in `.../site-packages/torch-1.5.0-py3.7-linux-x86_64.egg/torch`. Build with `.../site-packages/torch` fails because it is missing optimizer.h. I will not give further detail as I believe it will just complicate the issue unnecessarily. Any help is welcome.

**Comment by narendasan** [comment]
Are you able to import your custom built PyTorch on its own? It seems like the actual error has to do with missing symbols in PyTorch.

**Comment by narendasan** [comment]
For building TRTorch with CUDA 10 a couple modifications need to be made. I would advise using the local repository dependency path (https://nvidia.github.io/TRTorch/tutorials/installation.html#building-using-locally-installed-cudnn-tensorrt)

I would do the same for your locally built LibTorch, you can actually use the site packages directory as the source (This will only work for the Pre-CXX11-ABI compilation path) 

Replace this section:
https://github.com/NVIDIA/TRTorch/blob/29a4dbfb64848dae1d535f13df52185c794e5668/WORKSPACE#L35

With
```
new_local_repository(
    name = "libtorch_pre_cxx11_abi",
    path = ".../site-packages/torch",
    build_file = "@//third_party/libtorch:BUILD",
)
```
And if you are compiling for C++ build with the `bazel build //:libtrtorch --config pre_cxx11_abi`. For Python this is done for you. 

You also need to make the following line changes 
https://github.com/NVIDIA/TRTorch/blob/29a4dbfb64848dae1d535f13df52185c794e5668/WORKSPACE#L31 
This line needs to point to your CUDA 10.0 directory, 

https://github.com/NVIDIA/TRTorch/blob/29a4dbfb64848dae1d535f13df52185c794e5668/third_party/cuda/BUILD#L6
and this line needs to point to `cudart.so.10.0`

**Comment by esghif** [comment]
Thanks!

You were right the problem was with installing Pytorch for CUDA 10.0 with GLIBCXX_USE_CXX11_ABI=0. 
Issue description here: https://github.com/pytorch/pytorch/issues/31943
