### ISSUE TITLE
Implement a call function for the TRTEngine custom class

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#75]
Right now you need to use the `trt::execute_engine` op to run a TensorRT engine. Being able to run the engine class like a module may be nice. Code is stubbed out but need to find the right interface class for the function.

**Comment by lablabla** [comment]
@narendasan can you elaborate a bit more?
what do you mean by running as a module and where is the relevant code?

**Comment by narendasan** [comment]
We are considering a use case where people who load `trtorch` in python could use the `TRTEngine` class as an object encapsulating a TRT Engine. We want to have behavior where if I did something like 

```py
import torch
from torch import nn
import trtorch

class Example(nn.Module):
  def __init__(self):
     self.trt_mod = torch.classes.tensorrt.Engine(''''Arguments to instantiate engine""")
  def forward(self, x):
     return self.trt_mod(x)
```

Right now you need to do something like 

```py
import torch
from torch import nn
import trtorch

class Example(nn.Module):
  def __init__(self):
     self.trt_mod = torch.classes.tensorrt.Engine(''''Arguments to instantiate engine""")
  def forward(self, x):
     return torch.ops.tensorrt.execute_engine(self.trt_mod, [x])
```

The way to do this is to implement a `__call__` function in the TorchBind registration of TRTEngine here
https://github.com/NVIDIA/TRTorch/blob/3819c6a0e0fcf676d72b707bb18a49077ba913af/core/runtime/TRTEngine.cpp#L89

A related issue is https://github.com/NVIDIA/TRTorch/issues/46 which would let people pass in a arbitary serialized TRT engine
