### ISSUE TITLE
Create a lightweight runtime library

### ISSUE THREAD

**Issue by narendasan** [NVIDIA/TRTorch#77]
Now that serialization works, in deployment scenarios with limited resources, it would be nice to have a reduced size library which can run TRTorch modules. All that should be required is the execution section of the core library.

**Comment by xsacha** [comment]
What are the runtime requirements right now?
I notice that if I run it as-is in pytorch, I get:
```
Unknown type name '__torch__.torch.classes.tensorrt.Engine':
Serialized   File "code/__torch__/timm/models/resnet.py", line 3
class ResNet_trt(Module):
  __parameters__ = []
  __torch___timm_models_resnet_ResNet_trt_engine : __torch__.torch.classes.tensorrt.Engine
                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  def forward(self_1: __torch__.timm.models.resnet.ResNet_trt,
    input_0: Tensor) -> Tensor:
```

**Comment by narendasan** [comment]
You need to `import trtorch` for python or link against `libtrtorch.so` for C++ before loading compiled TorchScript files.

**Comment by xsacha** [comment]
Thanks, I couldn't find a trtorch.dll for Windows so had to build my own in order to distribute the runtime to Windows clients.
