### ISSUE TITLE
Does TRTorch support bail-out mechanism?

### ISSUE THREAD

**Issue by shiwenloong** [NVIDIA/TRTorch#79]
A neural network model may have some operators which aren't supported by TensorRT.
When TensorRT cannot compile a subgraph, can the execution of the subgraph invoke torch operators again? Can a model execution mix TensorRT and vanilla torch operators?

**Comment by narendasan** [comment]
Currently, we don't support automatic fallback on to TorchScript ops, but you are able to annotate modules in a way where you can use TRTorch compiled modules and TorchScript / PyTorch together. 

For example:
```py
import torch
from torch import nn
from torch.nn import functional as F
import trtorch
​
class LeNetFeatExtractor(nn.Module):
    def __init__(self):
        super(LeNetFeatExtractor, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
​
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        return x
​
class LeNetClassifier(nn.Module):
    def __init__(self):
        super(LeNetClassifier, self).__init__()
        self.fc1 = nn.Linear(16 * 6 * 6, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
​
    def forward(self, x):
        x = torch.flatten(x,1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
​
class LeNet(nn.Module):
    def __init__(self, freeze_feat_extractor=False, input_size=(1, 1, 32, 32)):
        super(LeNet, self).__init__()
        self.feat = LeNetFeatExtractor()
        if freeze_feat_extractor:
            self.feat.eval()
            self.feat = trtorch.compile(torch.jit.trace(self.feat, torch.randn(input_size)), extra_info={
                "input_shapes": [input_size]
            })
        self.classifer = LeNetClassifier()
​
    def forward(self, x):
        x = self.feat(x)
        x = self.classifer(x)
        return x
​
module = LeNet(freeze_feat_extractor=True).to("cuda")
```

We are discussing potentially supporting automatic fallback but right now this is the solution.

**Comment by shiwenloong** [comment]
> Currently, we don't support automatic fallback on to TorchScript ops, but you are able to annotate modules in a way where you can use TRTorch compiled modules and TorchScript / PyTorch together.
> 
> For example:
> 
> ```python
> import torch
> from torch import nn
> from torch.nn import functional as F
> import trtorch
> ​
> class LeNetFeatExtractor(nn.Module):
>     def __init__(self):
>         super(LeNetFeatExtractor, self).__init__()
>         self.conv1 = nn.Conv2d(1, 6, 3)
>         self.conv2 = nn.Conv2d(6, 16, 3)
> ​
>     def forward(self, x):
>         x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
>         x = F.max_pool2d(F.relu(self.conv2(x)), 2)
>         return x
> ​
> class LeNetClassifier(nn.Module):
>     def __init__(self):
>         super(LeNetClassifier, self).__init__()
>         self.fc1 = nn.Linear(16 * 6 * 6, 120)
>         self.fc2 = nn.Linear(120, 84)
>         self.fc3 = nn.Linear(84, 10)
> ​
>     def forward(self, x):
>         x = torch.flatten(x,1)
>         x = F.relu(self.fc1(x))
>         x = F.relu(self.fc2(x))
>         x = self.fc3(x)
>         return x
> ​
> class LeNet(nn.Module):
>     def __init__(self, freeze_feat_extractor=False, input_size=(1, 1, 32, 32)):
>         super(LeNet, self).__init__()
>         self.feat = LeNetFeatExtractor()
>         if freeze_feat_extractor:
>             self.feat.eval()
>             self.feat = trtorch.compile(torch.jit.trace(self.feat, torch.randn(input_size)), extra_info={
>                 "input_shapes": [input_size]
>             })
>         self.classifer = LeNetClassifier()
> ​
>     def forward(self, x):
>         x = self.feat(x)
>         x = self.classifer(x)
>         return x
> ​
> module = LeNet(freeze_feat_extractor=True).to("cuda")
> ```
> 
> We are discussing potentially supporting automatic fallback but right now this is the solution.

Thanks for your reply. It's very helpful.
