### ISSUE TITLE
Issues When Using Compiled Binaries

### ISSUE THREAD

**Issue by caelinsutch** [NVIDIA/TRTorch#90]
After compiling TRTorch on an x86 machine, and copying the outputted binaries to another machine, then using them in an include directory, I get the following error when compiling my code:
```
/usr/bin/ld: warning: libnvinfer.so.7, needed by /home/caelin/Github/br-core/ros2_ws/src/br-detection/include/trtorch/lib/libtrtorch.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.2, needed by /opt/ros/eloquent/lib/libcv_bridge.so, may conflict with libopencv_imgcodecs.so.4.2
/usr/bin/ld: warning: libopencv_imgproc.so.3.2, needed by /opt/ros/eloquent/lib/libcv_bridge.so, may conflict with libopencv_imgproc.so.4.2
/usr/bin/ld: warning: libopencv_core.so.3.2, needed by /opt/ros/eloquent/lib/libcv_bridge.so, may conflict with libopencv_core.so.4.2
/usr/bin/ld: warning: libopencv_calib3d.so.3.2, needed by /opt/ros/eloquent/lib/libimage_geometry.so, may conflict with libopencv_calib3d.so.4.2
/home/caelin/Github/br-core/ros2_ws/src/br-detection/include/trtorch/lib/libtrtorch.so: undefined reference to `createInferBuilder_INTERNAL'
/home/caelin/Github/br-core/ros2_ws/src/br-detection/include/trtorch/lib/libtrtorch.so: undefined reference to `createInferRuntime_INTERNAL'
```

**Comment by narendasan** [comment]
Do you have TensorRT installed on your target machine and the library path is an argument to the compiler? TRTorch doesn't statically link TensorRT so you will need that installed and available as well. The opencv issues aren't TRTorch issues but they probably have something to do with multiple opencv versions being installed/used and in the library path for the compiler.

**Comment by caelinsutch** [comment]
TensorRT is installed already. I'm guessing it's something to do with opencv versions as well

**Comment by xsacha** [comment]
It says libnvinfer.so is not found -- this is the error. Make sure it's in your LD_LIBRARY_PATH
