### ISSUE TITLE
What does it all mean Bazel?

### ISSUE THREAD

**Issue by oasisgunter** [NVIDIA/TRTorch#98]
Please specify what version to Bazel this needs to be built with?  Also please make sure you can actually compile that version for aarch64 on the Jetpacks Nvidia provides for its products.  If can't be compiled on aarch64 please fix this.  Nvidia should really do a better job of making sure its stuff is able to be compiled on its Jetpacks.  It would be nice if Nvidia would not use build systems which cannot be easily installed on their provided Jetpacks.  There is not simple command to install bazel.

**Comment by andi4191** [comment]
You can compile bazel on Jetson AGX using following commands:
```
curl -L https://github.com/bazelbuild/bazel/releases/download/3.2.0/bazel-3.2.0-dist.zip -o bazel-3.2.0-dist.zip 
mkdir -p temp && cd temp && unzip ../bazel-3.2.0-dist.zip
./compile.sh
```

Please refer https://github.com/NVIDIA/TRTorch#platform-support for Platform support updates.

**Comment by narendasan** [comment]
Refer to this issue for current instructions on aarch64 compilation #70, a more turn key solution is under development (#36)

**Comment by narendasan** [comment]
Reopen this issue if there are still problems running on aarch64
